-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Openmls.Extraction.Types
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open openmls

/-- [core::cmp::impls::{impl core::cmp::Eq for usize}::assert_fields_are_eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1906:12-1906:32
    Name pattern: [core::cmp::impls::{core::cmp::Eq<usize>}::assert_fields_are_eq]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::Eq<usize>}::assert_fields_are_eq"]
axiom Usize.Insts.CoreCmpEq.assert_fields_are_eq : Std.Usize → Result Unit

/-- [core::hash::impls::{impl core::hash::Hash for u32}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u32>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u32>}::hash"]
axiom U32.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U32 → H → Result H

/-- [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {B : Type} {I : Type} {F : Type} {B1 : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B1 B) :
  core.iter.adapters.map.Map I F → Result B1

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 831:4-834:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::num::{u32}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3755:8-3755:54
    Name pattern: [core::num::{u32}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{u32}::div_ceil"]
axiom core.num.U32.div_ceil : Std.U32 → Std.U32 → Result Std.U32

/-- [core::num::{u32}::is_multiple_of]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3840:8-3840:60
    Name pattern: [core::num::{u32}::is_multiple_of]
    Visibility: public -/
@[rust_fun "core::num::{u32}::is_multiple_of"]
axiom core.num.U32.is_multiple_of : Std.U32 → Std.U32 → Result Bool

/-- [alloc::vec::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::into_iter::IntoIter<T, A>}::collect]:
    Source: '/rustc/library/alloc/src/vec/into_iter.rs', lines 248:0-248:49
    Name pattern: [alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::collect]
    Visibility: public -/
@[rust_fun
  "alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::collect"]
axiom alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.collect
  {T : Type} {A : Type} {B : Type} (coreitertraitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B T) :
  alloc.vec.into_iter.IntoIter T → Result B

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2850:4-2850:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3085:4-3085:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [alloc::vec::{impl core::iter::traits::collect::IntoIterator<&'a T, core::slice::iter::Iter<'a, T>> for &'a alloc::vec::Vec<T>}::into_iter]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3981:4-3981:40
    Name pattern: [alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter"]
axiom SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (core.slice.iter.Iter T)

