-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: proof obligations
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls

@[spec]
theorem binary_tree.array_representation.treemath.level.spec.proof
  (index : Std.U32) :
  binary_tree.array_representation.treemath.level.spec index
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.root.spec.proof
  (size : binary_tree.array_representation.treemath.TreeSize) :
  binary_tree.array_representation.treemath.root.spec size
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.left.spec.proof
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  binary_tree.array_representation.treemath.left.spec index
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.right.spec.proof
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  binary_tree.array_representation.treemath.right.spec index
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.direct_path.spec.proof
   (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  binary_tree.array_representation.treemath.direct_path.spec node_index size
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.copath.spec.proof
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  binary_tree.array_representation.treemath.copath.spec leaf_index size
  := by sorry

@[spec]
theorem
  binary_tree.array_representation.treemath.lowest_common_ancestor.spec.proof
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  binary_tree.array_representation.treemath.lowest_common_ancestor.spec x y
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.common_direct_path.spec.proof
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  binary_tree.array_representation.treemath.common_direct_path.spec x y size
  := by sorry

@[spec]
theorem binary_tree.array_representation.treemath.is_node_in_tree.spec.proof
   (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  binary_tree.array_representation.treemath.is_node_in_tree.spec node_index
  size
  := by sorry

end openmls
