-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: specs (statements of correctness)
import Aeneas
import Hax
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls


/-- [openmls::binary_tree::array_representation::treemath::level::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 282:0-282:42 -/
@[reducible]
def binary_tree.array_representation.treemath.level.pre
  (index : Std.U32) : Result Bool := do
  let i ← 1#u32 <<< 31#i32
  ok (index < i)

/-- [openmls::binary_tree::array_representation::treemath::level::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 283:0-283:42 -/
@[reducible]
def binary_tree.array_representation.treemath.level.post
  (index : Std.U32) (result : Std.Usize) : Result Bool := do
  ok (result <= 31#usize)

def binary_tree.array_representation.treemath.level.spec (index : Std.U32)
  : Prop :=
  (binary_tree.array_representation.treemath.level.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.level index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.level.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::root::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 296:0-296:75 -/
@[reducible]
def binary_tree.array_representation.treemath.root.pre
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.TreeSize.u32 size
  if i > 0#u32
  then
    let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
    let i2 ← 2#u32 * i1
    let i3 ← i2 - 1#u32
    ok (i <= i3)
  else ok false

def binary_tree.array_representation.treemath.root.spec
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.root size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::left::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 303:0-303:53 -/
@[reducible]
def binary_tree.array_representation.treemath.left.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 index
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← i1 / 2#u32
  ok (i < i2)

def binary_tree.array_representation.treemath.left.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.left index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::right::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 312:0-312:53 -/
@[reducible]
def binary_tree.array_representation.treemath.right.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 index
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← i1 / 2#u32
  ok (i < i2)

def binary_tree.array_representation.treemath.right.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.right index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 354:0-354:97 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.pre
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.TreeSize.u32 size
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← 2#u32 * i1
  let i3 ← i2 - 1#u32
  if i <= i3
  then
    let i4 ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 node_index
    let i5 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i4 < i5)
  else ok false

def binary_tree.array_representation.treemath.direct_path.spec
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.direct_path.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.direct_path node_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::copath::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 369:0-369:97 -/
@[reducible]
def binary_tree.array_representation.treemath.copath.pre
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.TreeSize.u32 size
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← 2#u32 * i1
  let i3 ← i2 - 1#u32
  if i <= i3
  then
    let i4 ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
    let i5 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i4 < i5)
  else ok false

def binary_tree.array_representation.treemath.copath.spec
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.copath.pre leaf_index size).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.copath leaf_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 386:0-386:80 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← i1 / 2#u32
  if i < i2
  then
    let i3 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
    let i4 ← i1 / 2#u32
    ok (i3 < i4)
  else ok false

def binary_tree.array_representation.treemath.lowest_common_ancestor.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.lowest_common_ancestor.pre x
  y).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.lowest_common_ancestor x y
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::common_direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 409:0-409:119 -/
@[reducible]
def binary_tree.array_representation.treemath.common_direct_path.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.TreeSize.u32 size
  let i1 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i2 ← 2#u32 * i1
  let i3 ← i2 - 1#u32
  if i <= i3
  then
    let i4 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
    let i5 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    if i4 < i5
    then
      let i6 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i6 < i5)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.common_direct_path.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.common_direct_path.pre x y
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.common_direct_path x y size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 447:0-447:71 -/
@[reducible]
def binary_tree.array_representation.treemath.is_node_in_tree.post
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) (result : Bool) :
  Result Bool
  := do
  let i ←
    binary_tree.array_representation.treemath.TreeNodeIndex.u32 node_index
  let i1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
  ok (result = (i < i1))

def binary_tree.array_representation.treemath.is_node_in_tree.spec
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.is_node_in_tree node_index size
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.is_node_in_tree.post node_index
  size res).holds ⌝ ⦄

end openmls
