-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls


/-- [openmls::binary_tree::array_representation::treemath::level::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 335:0-335:34 -/
@[reducible]
def binary_tree.array_representation.treemath.level.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (index < i)

/-- [openmls::binary_tree::array_representation::treemath::level::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 336:0-336:56 -/
@[reducible]
def binary_tree.array_representation.treemath.level.post
  (index : Std.U32) (r : Std.Usize) : Result Bool := do
  if r <= 31#usize
  then if r = 0#usize
       then let i ← index % 2#u32
            ok (i = 0#u32)
       else ok true
  else ok false

def binary_tree.array_representation.treemath.level.spec (index : Std.U32)
  : Prop :=
  (binary_tree.array_representation.treemath.level.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.level index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.level.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::root::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 349:0-349:25 -/
@[reducible]
def binary_tree.array_representation.treemath.root.pre
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid size

def binary_tree.array_representation.treemath.root.spec
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.root size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::left::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 356:0-356:26 -/
@[reducible]
def binary_tree.array_representation.treemath.left.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

def binary_tree.array_representation.treemath.left.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.left index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::right::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 365:0-365:26 -/
@[reducible]
def binary_tree.array_representation.treemath.right.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

def binary_tree.array_representation.treemath.right.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.right index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::parent::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 376:0-376:22 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.pre
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid x

/-- [openmls::binary_tree::array_representation::treemath::parent::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 377:0-377:35 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.post
  (x : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 r
  let i1 ← binary_tree.array_representation.treemath.MAX_INDEX
  ok (i < i1)

def binary_tree.array_representation.treemath.parent.spec
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.parent.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.parent x
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.parent.post x res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::sibling::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 393:0-393:26 -/
@[reducible]
def binary_tree.array_representation.treemath.sibling.pre
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid index

def binary_tree.array_representation.treemath.sibling.spec
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.sibling.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.sibling index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 411:0-411:65 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.pre
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 node_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::direct_path::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 412:0-414:30 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.post
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize)
  (result : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Prop
  := do
  let len ← alloc.vec.Vec.len result
  pure <| (len ≤ 30#usize) ∧ (∀ i < len, (do
    let x ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) result i
    x.valid
  ).holds)

def binary_tree.array_representation.treemath.direct_path.spec
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.direct_path.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.direct_path node_index size
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.direct_path.post node_index size
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::copath::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 429:0-429:65 -/
@[reducible]
def binary_tree.array_representation.treemath.copath.pre
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.copath.spec
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.copath.pre leaf_index size).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.copath leaf_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 446:0-446:57 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.LeafNodeIndex.valid x
  if b
  then
    let b1 ← binary_tree.array_representation.treemath.LeafNodeIndex.valid y
    if b1
    then
      let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
      let i1 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i != i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.lowest_common_ancestor.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.lowest_common_ancestor.pre x
  y).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.lowest_common_ancestor x y
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::common_direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 469:0-469:88 -/
@[reducible]
def binary_tree.array_representation.treemath.common_direct_path.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    if i < i1
    then
      let i2 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i2 < i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.common_direct_path.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.common_direct_path.pre x y
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.common_direct_path x y size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 507:0-507:31 -/
@[reducible]
def binary_tree.array_representation.treemath.is_node_in_tree.pre
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid node_index

def binary_tree.array_representation.treemath.is_node_in_tree.spec
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.is_node_in_tree.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.is_node_in_tree node_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 65:4-65:29 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid self_

def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index self
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 71:4-71:36 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 0#u32)

def
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 107:4-107:29 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid self_

def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index self
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 113:4-113:36 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 1#u32)

def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 185:4-185:29 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid self_

def binary_tree.array_representation.treemath.TreeNodeIndex.u32.spec
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre self).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.u32 self
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 240:4-240:38 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.pre
  (nodes : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (nodes < i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 241:4-241:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.post
  (nodes : Std.U32)
  (result : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid result

def binary_tree.array_representation.treemath.TreeSize.new.spec
  (nodes : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.new.pre nodes).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.new nodes
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.new.post nodes res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 275:4-275:43 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i1 ← i / 2#u32
  ok (self_ < i1)

def binary_tree.array_representation.treemath.TreeSize.inc.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.inc.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.inc self
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 281:4-281:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  ok (binary_tree.array_representation.treemath.MIN_TREE_SIZE < self_)

def binary_tree.array_representation.treemath.TreeSize.dec.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.dec.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.dec self
  ⦃ ⇓ res => ⌜ True ⌝ ⦄

end openmls
