-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace openmls

/-- [openmls::binary_tree::array_representation::treemath::LeafNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 26:0-26:30
    Visibility: public -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex := Std.U32

/-- [openmls::binary_tree::array_representation::treemath::ParentNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 64:0-64:32
    Visibility: public -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex := Std.U32

/-- [openmls::binary_tree::array_representation::treemath::TreeNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 124:0-127:1
    Visibility: public -/
@[discriminant isize]
inductive binary_tree.array_representation.treemath.TreeNodeIndex where
| Leaf :
  binary_tree.array_representation.treemath.LeafNodeIndex →
  binary_tree.array_representation.treemath.TreeNodeIndex
| Parent :
  binary_tree.array_representation.treemath.ParentNodeIndex →
  binary_tree.array_representation.treemath.TreeNodeIndex

/-- [openmls::binary_tree::array_representation::treemath::TreeSize]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 185:0-185:32 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize := Std.U32

end openmls
