-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open openmls

/-! ## External functions

These are the `core`/`alloc` operations that the current `CoreModels` library does
not provide under the names this extraction references. They are modelled as axioms,
in the spirit of an Aeneas `FunsExternal` file. Signatures are chosen to match the
exact call sites in `Funs.lean` (treemath). -/

/- ### `u32` arithmetic / ordering / hashing -/

/-- `<u32 as Ord>::cmp` -/
axiom core.U32.Insts.CoreCmpOrd.cmp : Std.U32 → Std.U32 → Result core.cmp.Ordering

/-- `<u32 as Hash>::hash` -/
axiom core.U32.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U32 → H → Result H

/-- `u32::is_multiple_of` — faithful total model. `n.is_multiple_of m ↔ n % m == 0`;
    since `Nat`'s `_ % 0 = id`, this also gives Rust's `m = 0 ⇒ (n == 0)` behaviour. -/
def core.num.U32.is_multiple_of (x y : Std.U32) : Result Bool :=
  ok (decide (x.val % y.val = 0))

/-- `u32::div_ceil` -/
axiom core.num.U32.div_ceil : Std.U32 → Std.U32 → Result Std.U32

/- ### Slice indexing on `Vec` -/

/-- `SliceIndex<[T]>` witness (only ever threaded through `Index::index`). -/
axiom core.slice.index.SliceIndex (Self : Type) (Container : Type) (Output : Type) : Type

/-- `<usize as SliceIndex<[T]>>` -/
axiom core.Usize.Insts.CoreSliceIndexSliceIndexSliceT (T : Type) :
  core.slice.index.SliceIndex Std.Usize (Slice T) T

/-- `<Vec<T> as Index<I>>::index` (here `I = usize`, `Output = T`). -/
axiom alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
  {T : Type} {Output : Type}
  (sliceIndexInst : core.slice.index.SliceIndex Std.Usize (Slice T) Output)
  (self : alloc.vec.Vec T) (index : Std.Usize) : Result Output

/-- `<Vec<T> as DerefMut>::deref_mut` — returns the slice view together with the
    write-back closure (Aeneas mutable-borrow encoding). -/
axiom alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut
  {T : Type} (self : alloc.vec.Vec T) :
  Result ((Slice T) × ((Slice T) → alloc.vec.Vec T))

/-- `<[T]>::reverse`. Aeneas' own `core.slice.Slice.reverse` is a total function
    returning a bare `Slice T` (reversal never fails), but it lives in `Aeneas.Std` and
    is shadowed here by `open Aeneas.Std hiding namespace core`; the call sites in
    `Funs.lean` also bind it monadically (`←`), so the model must be `Result`-valued.
    We reuse the real Aeneas definition wrapped in `ok` — a faithful total model, not a
    new trusted axiom. The `_root_.` prefix is required so the name lands at top level
    (otherwise the open captures the `core.slice.Slice` prefix as the `Slice` type's
    namespace); `Funs.lean`'s `hiding namespace core` then resolves to this model. -/
def _root_.core.slice.Slice.reverse {T : Type} (s : Slice T) : Result (Slice T) :=
  ok (Aeneas.Std.core.slice.Slice.reverse s)

/-- `<usize as Ord>` (instance witness, used by `core::cmp::min`). -/
axiom core.Usize.Insts.CoreCmpOrd : core.cmp.Ord Std.Usize

/- ### Iterators (slice iter, vec into-iter, map adapter) -/

/-- `<slice::Iter<'_, T> as Iterator>::next` -/
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next
  {T : Type} : core.slice.iter.Iter T →
  Result ((core.option.Option T) × (core.slice.iter.Iter T))

/-- `<&Vec<T> as IntoIterator>::into_iter` -/
axiom alloc.SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} : alloc.vec.Vec T → Result (core.slice.iter.Iter T)

/-- `<Vec<T> as IntoIterator>::into_iter` -/
axiom alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
  {T : Type} : alloc.vec.Vec T → Result (alloc.vec.into_iter.IntoIter T)

/-- `vec::IntoIter<T>` is an `Iterator` (instance witness). -/
axiom alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator (T : Type) :
  core.iter.traits.iterator.Iterator (alloc.vec.into_iter.IntoIter T) T

/-- `Vec<T>` is a `FromIterator<T>` target (instance witness). -/
axiom alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator (T : Type) :
  core.iter.traits.collect.FromIterator (alloc.vec.Vec T) T

/-- `<vec::IntoIter<T> as Iterator>::map` — `F` is the closure type, witnessed by
    its `FnMut` instance. -/
axiom alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
  {T : Type} {O : Type} {F : Type}
  (FnMutInst : Std.core.ops.function.FnMut F T O)
  (self : alloc.vec.into_iter.IntoIter T) (f : F) :
  Result (core.iter.adapters.map.Map (alloc.vec.into_iter.IntoIter T) F)

/-- `<Map<I, F> as Iterator>::collect` — target collection `B` is fixed by the
    `FromIterator` witness. -/
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {I : Type} {Item : Type} {O : Type} {F : Type} {B : Type}
  (IteratorInst : core.iter.traits.iterator.Iterator I Item)
  (FnMutInst : Std.core.ops.function.FnMut F Item O)
  (FromIteratorInst : core.iter.traits.collect.FromIterator B O) :
  core.iter.adapters.map.Map I F → Result B
