-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open openmls

/-! ## External functions

The `core`/`alloc` iterator operations that `CoreModels` does not provide under the names
this extraction references. Signatures match the exact call sites in `Funs.lean` (treemath).
Every other external operation the extraction uses resolves by bare name to a concrete
upstream `CoreModels` definition (pin: `cryspen/hax`, branch `openmls-core-models`), and its
spec is PROVED against that upstream body in `Openmls/Proofs/MissingCoreSpecs.lean` — see
the campaign record in `Openmls/Proofs/HANDOFF.md` for the history.

Three entries: the two lazy `Iterator::map` adapters (faithful total *definitions*, not
axioms) and the single remaining trusted `axiom`,
`core.iter.adapters.map.Map.…​.collect`. -/

/-- `<vec::IntoIter<T> as Iterator>::map` — faithful total MODEL (a definition, not an axiom):
    Rust's `Iterator::map` is lazy, it merely *packages* the receiver iterator together with the
    closure, and `CoreModels`' `core.iter.adapters.map.Map I F` is exactly that pair structure
    `{ iter : I, f : F }` (`CoreModels/Core/Types.lean`). So the semantics is `ok ⟨self, f⟩`; no
    element is consumed and the call cannot fail. `F` is the closure type, witnessed by its
    `FnMut` instance — kept (unused) so the generated call sites in `Funs.lean` still elaborate. -/
def alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
  {T : Type} {O : Type} {F : Type}
  (FnMutInst : Std.core.ops.function.FnMut F T O)
  (self : alloc.vec.into_iter.IntoIter T) (f : F) :
  Result (core.iter.adapters.map.Map (alloc.vec.into_iter.IntoIter T) F) :=
  ok ⟨self, f⟩

/-- `<slice::Iter<'_, T> as Iterator>::map` — faithful total MODEL (a definition, not an axiom),
    for the same reason as the `vec::IntoIter` twin above: Rust's `map` is lazy and only pairs the
    iterator with the closure, which is precisely the `core.iter.adapters.map.Map` structure
    `{ iter : I, f : F }`. Hence `ok ⟨self, f⟩`. `F` is the closure *state* type (e.g. `Unit` for a
    non-capturing closure), witnessed by its CoreModels `FnMut` instance — kept (unused) so the
    generated call sites still elaborate. Used since the `copath` rewrite maps an extracted closure
    over a slice iterator. -/
def core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
  {T : Type} {O : Type} {F : Type}
  (FnMutInst : CoreModels.core.ops.function.FnMut F T O)
  (self : core.slice.iter.Iter T) (f : F) :
  Result (core.iter.adapters.map.Map (core.slice.iter.Iter T) F) :=
  ok ⟨self, f⟩

/-- `<Map<I, F> as Iterator>::collect` — target collection `B` is fixed by the
    `FromIterator` witness. The `FnMut` witness parameter is type-generic (`W`) because the
    extraction mixes two `FnMut` families at the two call sites: `Aeneas.Std`'s (via
    `BuiltinFnMut`, for the plain-function `sibling` map) and `CoreModels`' (for real
    extracted closures); `Item`/`O` are already pinned by the other two witnesses. -/
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {I : Type} {Item : Type} {O : Type} {F : Type} {B : Type} {W : Type}
  (IteratorInst : core.iter.traits.iterator.Iterator I Item)
  (FnMutInst : W)
  (FromIteratorInst : core.iter.traits.collect.FromIterator B O) :
  core.iter.adapters.map.Map I F → Result B
