-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls


/-- [openmls::binary_tree::array_representation::treemath::level::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 369:0-369:34 -/
@[reducible]
def binary_tree.array_representation.treemath.level.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (index < i)

/-- [openmls::binary_tree::array_representation::treemath::level::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 370:0-370:71 -/
@[reducible]
def binary_tree.array_representation.treemath.level.post
  (index : Std.U32) (r : Std.Usize) : Result Bool := do
  if r <= 30#usize
  then
    let i ← r + 1#usize
    let i1 ← 1#u32 <<< i
    let i2 ← index % i1
    let i3 ← 1#u32 <<< r
    let i4 ← i3 - 1#u32
    ok (i2 = i4)
  else ok false

def binary_tree.array_representation.treemath.level.spec (index : Std.U32)
  : Prop :=
  (binary_tree.array_representation.treemath.level.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.level index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.level.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::root::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 383:0-383:25 -/
@[reducible]
def binary_tree.array_representation.treemath.root.pre
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid size

/-- [openmls::binary_tree::array_representation::treemath::root::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 384:0-384:49 -/
@[reducible]
def binary_tree.array_representation.treemath.root.post
  (size : binary_tree.array_representation.treemath.TreeSize)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.root.spec
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.root size
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.root.post size res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::left::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 391:0-391:26 -/
@[reducible]
def binary_tree.array_representation.treemath.left.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::left::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 392:0-392:60 -/
@[reducible]
def binary_tree.array_representation.treemath.left.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.left.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.left index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.left.post index res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::right::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 401:0-401:26 -/
@[reducible]
def binary_tree.array_representation.treemath.right.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::right::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 402:0-402:60 -/
@[reducible]
def binary_tree.array_representation.treemath.right.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i > i1)
  else ok false

def binary_tree.array_representation.treemath.right.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.right index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.right.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::parent::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 413:0-413:22 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.pre
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid x

/-- [openmls::binary_tree::array_representation::treemath::parent::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 416:0-418:53 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.post
  (x : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 r
  let i1 ← binary_tree.array_representation.treemath.MAX_PARENT
  let i2 ← i1 + 1#u32
  if i <= i2
  then
    let i3 ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 x
    let i4 ← binary_tree.array_representation.treemath.MAX_ROOT_INDEX
    if i3 = i4
    then
      let i5 ← 2#u32 * i
      let i6 ← i5 + 1#u32
      let i7 ← binary_tree.array_representation.treemath.level i6
      let i8 ← binary_tree.array_representation.treemath.level i3
      let i9 ← i8 + 1#usize
      ok (i7 = i9)
    else
      let b ←
        binary_tree.array_representation.treemath.ParentNodeIndex.valid r
      if b
      then
        let i5 ← 2#u32 * i
        let i6 ← i5 + 1#u32
        let i7 ← binary_tree.array_representation.treemath.level i6
        let i8 ← binary_tree.array_representation.treemath.level i3
        let i9 ← i8 + 1#usize
        ok (i7 = i9)
      else ok false
  else ok false

def binary_tree.array_representation.treemath.parent.spec
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.parent.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.parent x
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.parent.post x res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::sibling::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 434:0-434:59 -/
@[reducible]
def binary_tree.array_representation.treemath.sibling.pre
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid index
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 index
    let i1 ← binary_tree.array_representation.treemath.MAX_ROOT_INDEX
    ok (i != i1)
  else ok false

def binary_tree.array_representation.treemath.sibling.spec
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.sibling.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.sibling index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 452:0-452:65 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.pre
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 node_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::direct_path::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 453:0-457:30 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.post
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize)
  (result : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Prop
  := do
  let len ← alloc.vec.Vec.len result
  pure <| (len ≤ 30#usize) ∧ (∀ i < len, (do
    let x ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) result i
    x.valid
  ).holds) ∧ (∀ i < len, (do
    let x ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) result i
    let xi ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 x
    let pc ←
      binary_tree.array_representation.treemath.TreeSize.parent_count size
    ok (xi < pc)
  ).holds)

def binary_tree.array_representation.treemath.direct_path.spec
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.direct_path.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.direct_path node_index size
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.direct_path.post node_index size
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::copath::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 472:0-472:65 -/
@[reducible]
def binary_tree.array_representation.treemath.copath.pre
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.copath.spec
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.copath.pre leaf_index size).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.copath leaf_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 491:0-491:57 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.LeafNodeIndex.valid x
  if b
  then
    let b1 ← binary_tree.array_representation.treemath.LeafNodeIndex.valid y
    if b1
    then
      let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
      let i1 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i != i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.lowest_common_ancestor.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.lowest_common_ancestor.pre x
  y).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.lowest_common_ancestor x y
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::common_direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 514:0-514:88 -/
@[reducible]
def binary_tree.array_representation.treemath.common_direct_path.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    if i < i1
    then
      let i2 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i2 < i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.common_direct_path.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.common_direct_path.pre x y
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.common_direct_path x y size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 552:0-552:31 -/
@[reducible]
def binary_tree.array_representation.treemath.is_node_in_tree.pre
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid node_index

def binary_tree.array_representation.treemath.is_node_in_tree.spec
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.is_node_in_tree.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.is_node_in_tree node_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 88:4-88:29 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 89:4-89:72 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ * 2#u32
  if r = i
  then
    let i1 ← r % 2#u32
    if i1 = 0#u32
    then
      let i2 ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
      ok (r <= i2)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 95:4-95:36 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 0#u32)

def
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 131:4-131:29 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 132:4-132:75 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ * 2#u32
  let i1 ← i + 1#u32
  if r = i1
  then
    let i2 ← r % 2#u32
    if i2 = 1#u32
    then
      let i3 ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
      ok (r < i3)
    else ok false
  else ok false

def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 138:4-138:36 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 1#u32)

def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 195:4-195:55 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.new.post
  (index : Std.U32)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  if index > i
  then ok true
  else binary_tree.array_representation.treemath.TreeNodeIndex.valid r

def binary_tree.array_representation.treemath.TreeNodeIndex.new.spec
  (index : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.new index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.new.post index
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 211:4-211:29 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 212:4-212:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.post
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  ok (r <= i)

def binary_tree.array_representation.treemath.TreeNodeIndex.u32.spec
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre self).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.u32 self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.post self
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 271:4-271:38 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.pre
  (nodes : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (nodes < i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 272:4-272:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.post
  (nodes : Std.U32)
  (result : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid result

def binary_tree.array_representation.treemath.TreeSize.new.spec
  (nodes : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.new.pre nodes).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.new nodes
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.new.post nodes res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::leaf_count::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 285:4-285:81 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.leaf_count.post
  (self_ : binary_tree.array_representation.treemath.TreeSize) (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ / 2#u32
  let i1 ← i + 1#u32
  if r = i1
  then
    let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
    if b
    then
      let i2 ← binary_tree.array_representation.treemath.MAX_LEAF_COUNT
      ok (r <= i2)
    else ok true
  else ok false

def binary_tree.array_representation.treemath.TreeSize.leaf_count.spec
   (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.leaf_count self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.leaf_count.post self
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 307:4-307:59 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then
    let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
    let i1 ← i / 2#u32
    ok (self_ < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 308:4-308:76 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ * 2#u32
       let i1 ← i + 1#u32
       ok (self__future = i1)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.inc.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.inc.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.inc self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.inc.post self res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 314:4-314:55 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then ok (binary_tree.array_representation.treemath.MIN_TREE_SIZE < self_)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 315:4-315:72 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ / 2#u32
       ok (self__future = i)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.dec.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.dec.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.dec self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.dec.post self res).holds
  ⌝ ⦄

end openmls
