-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls


/-- [openmls::binary_tree::array_representation::treemath::level::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 346:0-346:34 -/
@[reducible]
def binary_tree.array_representation.treemath.level.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (index < i)

/-- [openmls::binary_tree::array_representation::treemath::level::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 347:0-347:71 -/
@[reducible]
def binary_tree.array_representation.treemath.level.post
  (index : Std.U32) (r : Std.Usize) : Result Bool := do
  if r <= 30#usize
  then
    let i ← r + 1#usize
    let i1 ← 1#u32 <<< i
    let i2 ← index % i1
    let i3 ← 1#u32 <<< r
    let i4 ← i3 - 1#u32
    ok (i2 = i4)
  else ok false

def binary_tree.array_representation.treemath.level.spec (index : Std.U32)
  : Prop :=
  (binary_tree.array_representation.treemath.level.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.level index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.level.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::root::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 360:0-360:25 -/
@[reducible]
def binary_tree.array_representation.treemath.root.pre
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid size

/-- [openmls::binary_tree::array_representation::treemath::root::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 361:0-361:49 -/
@[reducible]
def binary_tree.array_representation.treemath.root.post
  (size : binary_tree.array_representation.treemath.TreeSize)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.root.spec
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.root size
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.root.post size res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::left::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 368:0-368:26 -/
@[reducible]
def binary_tree.array_representation.treemath.left.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::left::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 369:0-369:60 -/
@[reducible]
def binary_tree.array_representation.treemath.left.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.left.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.left index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.left.post index res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::right::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 378:0-378:26 -/
@[reducible]
def binary_tree.array_representation.treemath.right.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::right::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 379:0-379:60 -/
@[reducible]
def binary_tree.array_representation.treemath.right.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i > i1)
  else ok false

def binary_tree.array_representation.treemath.right.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.right index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.right.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::parent::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 390:0-390:22 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.pre
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid x

/-- [openmls::binary_tree::array_representation::treemath::parent::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 393:0-395:53 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.post
  (x : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 r
  let i1 ← binary_tree.array_representation.treemath.MAX_INDEX
  if i < i1
  then
    let i2 ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 x
    let i3 ← i1 - 1#u32
    if i2 = i3
    then
      let i4 ← 2#u32 * i
      let i5 ← i4 + 1#u32
      let i6 ← binary_tree.array_representation.treemath.level i5
      let i7 ← binary_tree.array_representation.treemath.level i2
      let i8 ← i7 + 1#usize
      ok (i6 = i8)
    else
      let b ←
        binary_tree.array_representation.treemath.ParentNodeIndex.valid r
      if b
      then
        let i4 ← 2#u32 * i
        let i5 ← i4 + 1#u32
        let i6 ← binary_tree.array_representation.treemath.level i5
        let i7 ← binary_tree.array_representation.treemath.level i2
        let i8 ← i7 + 1#usize
        ok (i6 = i8)
      else ok false
  else ok false

def binary_tree.array_representation.treemath.parent.spec
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.parent.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.parent x
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.parent.post x res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::sibling::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 411:0-411:58 -/
@[reducible]
def binary_tree.array_representation.treemath.sibling.pre
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid index
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 index
    let i1 ← binary_tree.array_representation.treemath.MAX_INDEX
    let i2 ← i1 - 1#u32
    ok (i != i2)
  else ok false

def binary_tree.array_representation.treemath.sibling.spec
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.sibling.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.sibling index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 429:0-429:65 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.pre
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 node_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::direct_path::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 430:0-434:30 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.post
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize)
  (result : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Prop
  := do
  let len ← alloc.vec.Vec.len result
  pure <| (len ≤ 30#usize) ∧ (∀ i < len, (do
    let x ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) result i
    x.valid
  ).holds) ∧ (∀ i < len, (do
    let x ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) result i
    let xi ← binary_tree.array_representation.treemath.ParentNodeIndex.u32 x
    let pc ←
      binary_tree.array_representation.treemath.TreeSize.parent_count size
    ok (xi < pc)
  ).holds)

def binary_tree.array_representation.treemath.direct_path.spec
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.direct_path.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.direct_path node_index size
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.direct_path.post node_index size
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::copath::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 449:0-449:65 -/
@[reducible]
def binary_tree.array_representation.treemath.copath.pre
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.copath.spec
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.copath.pre leaf_index size).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.copath leaf_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 468:0-468:57 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.LeafNodeIndex.valid x
  if b
  then
    let b1 ← binary_tree.array_representation.treemath.LeafNodeIndex.valid y
    if b1
    then
      let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
      let i1 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i != i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.lowest_common_ancestor.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.lowest_common_ancestor.pre x
  y).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.lowest_common_ancestor x y
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::common_direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 491:0-491:88 -/
@[reducible]
def binary_tree.array_representation.treemath.common_direct_path.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    if i < i1
    then
      let i2 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i2 < i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.common_direct_path.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.common_direct_path.pre x y
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.common_direct_path x y size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 529:0-529:31 -/
@[reducible]
def binary_tree.array_representation.treemath.is_node_in_tree.pre
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid node_index

def binary_tree.array_representation.treemath.is_node_in_tree.spec
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.is_node_in_tree.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.is_node_in_tree node_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 65:4-65:29 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 66:4-66:74 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ * 2#u32
  if r = i
  then
    let i1 ← r % 2#u32
    if i1 = 0#u32
    then
      let i2 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
      let i3 ← i2 - 1#u32
      ok (r < i3)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 72:4-72:36 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 0#u32)

def
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:4-108:29 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 109:4-109:78 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ * 2#u32
  let i1 ← i + 1#u32
  if r = i1
  then
    let i2 ← r % 2#u32
    if i2 = 1#u32
    then
      let i3 ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
      let i4 ← i3 - 2#u32
      ok (r < i4)
    else ok false
  else ok false

def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 115:4-115:36 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  ok (i = 1#u32)

def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 172:4-172:61 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.new.post
  (index : Std.U32)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Prop
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  pure <| index < i → b

def binary_tree.array_representation.treemath.TreeNodeIndex.new.spec
  (index : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.new index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.new.post index
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 188:4-188:29 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 189:4-189:41 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.post
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  let i1 ← i - 1#u32
  ok (r < i1)

def binary_tree.array_representation.treemath.TreeNodeIndex.u32.spec
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre self).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.u32 self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.post self
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 248:4-248:38 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.pre
  (nodes : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (nodes < i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 249:4-249:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.post
  (nodes : Std.U32)
  (result : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid result

def binary_tree.array_representation.treemath.TreeSize.new.spec
  (nodes : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.new.pre nodes).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.new nodes
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.new.post nodes res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::leaf_count::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:4-262:76 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.leaf_count.post
  (self_ : binary_tree.array_representation.treemath.TreeSize) (r : Std.U32) :
  Result Bool
  := do
  let i ← self_ / 2#u32
  let i1 ← i + 1#u32
  if r = i1
  then
    let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
    if b
    then
      let i2 ← binary_tree.array_representation.treemath.MAX_INDEX
      ok (r <= i2)
    else ok true
  else ok false

def binary_tree.array_representation.treemath.TreeSize.leaf_count.spec
   (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.leaf_count self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.leaf_count.post self
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 284:4-284:59 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then
    let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
    let i1 ← i / 2#u32
    ok (self_ < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 285:4-285:76 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ * 2#u32
       let i1 ← i + 1#u32
       ok (self__future = i1)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.inc.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.inc.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.inc self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.inc.post self res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 291:4-291:55 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then ok (binary_tree.array_representation.treemath.MIN_TREE_SIZE < self_)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 292:4-292:72 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ / 2#u32
       ok (self__future = i)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.dec.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.dec.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.dec self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.dec.post self res).holds
  ⌝ ⦄

end openmls
