-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: type definitions
import Aeneas
import CoreModels
import Openmls.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace openmls

/-- [openmls::binary_tree::array_representation::treemath::LeafNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 31:0-31:30
    Visibility: public -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex := Std.U32

/-- [openmls::binary_tree::array_representation::treemath::ParentNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 81:0-81:32
    Visibility: public -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex := Std.U32

/-- [openmls::binary_tree::array_representation::treemath::TreeNodeIndex]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 153:0-156:1
    Visibility: public -/
@[discriminant isize]
inductive binary_tree.array_representation.treemath.TreeNodeIndex where
| Leaf :
  binary_tree.array_representation.treemath.LeafNodeIndex →
  binary_tree.array_representation.treemath.TreeNodeIndex
| Parent :
  binary_tree.array_representation.treemath.ParentNodeIndex →
  binary_tree.array_representation.treemath.TreeNodeIndex

/-- [openmls::binary_tree::array_representation::treemath::TreeSize]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 229:0-229:32 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize := Std.U32

/-- [openmls::binary_tree::array_representation::treemath::_#20::ensures::closure#1]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 432:16-433:46 -/
def binary_tree.array_representation.treemath.__20.ensures.closure_1 :=
  alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex ×
  binary_tree.array_representation.treemath.TreeSize

/-- [openmls::binary_tree::array_representation::treemath::_#20::ensures::closure]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 431:11-431:66 -/
@[reducible]
def binary_tree.array_representation.treemath.__20.ensures.closure :=
  alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex

end openmls
