name = "Openmls"
version = "0.1.0"
defaultTargets = ["Openmls"]

[[lean_lib]]
name = "Openmls"
roots = ["Openmls"]

[[require]]
name = "hax"
git = "https://github.com/cryspen/hax-lean"
rev = "ea3e420405c7bd281e3acbf24a54ebd0bb2fec33"