name = "Openmls"
version = "0.1.0"
defaultTargets = ["Openmls"]

[[lean_lib]]
name = "Openmls"
roots = ["Openmls"]

[[require]]
name = "hax"
git = "https://github.com/cryspen/hax"
rev = "openmls-core-models"
subDir = "hax-lib/proof-libs/lean"