-- [openmls]: pure-`Nat` / bit-arithmetic lemmas (concern B).
-- No monad, no Aeneas `Result` — just the trailing-ones count `tones` and the `parent` bit-expression
-- arithmetic underpinning the treemath value specs. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-- `1 <<< k` (as `u32`) is nonzero whenever the shift amount is in range. -/
theorem one_le_one_shiftLeft_mod (k : Nat) (h : k < 32) :
    1 ≤ 1 <<< k % Aeneas.Std.U32.size := by
  have e : 1 <<< k = 2 ^ k := by simp [Nat.shiftLeft_eq]
  have h2 : (2 : Nat) ^ 31 < Aeneas.Std.U32.size := by native_decide
  have hle : (2 : Nat) ^ k ≤ 2 ^ 31 := Nat.pow_le_pow_right (by norm_num) (by omega)
  rw [e, Nat.mod_eq_of_lt (by omega)]
  exact Nat.one_le_two_pow

/-- `(2^k − 1) mod 2^j = 2^j − 1` when `j ≤ k` (the low `j` bits of `2^k−1` are all 1). -/
theorem pow_sub_one_mod (j k : Nat) (h : j ≤ k) :
    (2 ^ k - 1) % 2 ^ j = 2 ^ j - 1 := by
  have hjk : 2 ^ j * 2 ^ (k - j) = 2 ^ k := by rw [← pow_add]; congr 1; omega
  have hjle : 2 ^ j ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) h
  have hj1 : 1 ≤ 2 ^ j := Nat.one_le_two_pow
  have e : 2 ^ k - 1 = 2 ^ j * (2 ^ (k - j) - 1) + (2 ^ j - 1) := by
    rw [Nat.mul_sub, mul_one, hjk]; omega
  rw [e, Nat.mul_add_mod, Nat.mod_eq_of_lt (by omega)]

/-- The trailing-ones count `m` with `a % 2^(m+1) = 2^m − 1` is unique. -/
theorem trailing_unique (a m n : Nat)
    (hm : a % 2 ^ (m + 1) = 2 ^ m - 1)
    (hn : a % 2 ^ (n + 1) = 2 ^ n - 1) : m = n := by
  rcases Nat.lt_trichotomy m n with h | h | h
  · exfalso
    have hdvd : 2 ^ (m + 1) ∣ 2 ^ (n + 1) := pow_dvd_pow 2 (by omega)
    have := Nat.mod_mod_of_dvd a hdvd
    rw [hn, pow_sub_one_mod (m + 1) n (by omega)] at this
    rw [hm] at this
    have : (2:Nat) ^ m < 2 ^ (m + 1) := Nat.pow_lt_pow_right (by norm_num) (by omega)
    have : 1 ≤ (2:Nat) ^ m := Nat.one_le_two_pow
    omega
  · exact h
  · exfalso
    have hdvd : 2 ^ (n + 1) ∣ 2 ^ (m + 1) := pow_dvd_pow 2 (by omega)
    have := Nat.mod_mod_of_dvd a hdvd
    rw [hm, pow_sub_one_mod (n + 1) m (by omega)] at this
    rw [hn] at this
    have : (2:Nat) ^ n < 2 ^ (n + 1) := Nat.pow_lt_pow_right (by norm_num) (by omega)
    have : 1 ≤ (2:Nat) ^ n := Nat.one_le_two_pow
    omega

/-- `parent`'s bit expression equals a pure high/low OR split of `X`. -/
theorem parent_bitops_eq (X k : Nat) (hk : X % 2 ^ (k + 1) = 2 ^ k - 1) :
    (X ||| 2 ^ k) ^^^ ((X >>> (k + 1) &&& 1) <<< (k + 1))
      = ((X >>> (k + 2)) <<< (k + 2)) ||| (2 ^ (k + 1) - 1) := by
  have h1bit : ∀ m, (1:Nat).testBit m = decide (m = 0) := by
    intro m; rw [show (1:Nat) = 2 ^ 0 from rfl, Nat.testBit_two_pow]; simp [eq_comm]
  have hlow : ∀ j, j ≤ k → X.testBit j = decide (j < k) := by
    intro j hj
    have h1 := Nat.testBit_mod_two_pow X (k + 1) j
    rw [hk, Nat.testBit_two_pow_sub_one] at h1
    have hj1 : j < k + 1 := by omega
    simp only [hj1, decide_true, Bool.true_and] at h1
    exact h1.symm
  refine Nat.eq_of_testBit_eq fun j => ?_
  simp only [Nat.testBit_lor, Nat.testBit_xor, Nat.testBit_two_pow, Nat.testBit_shiftLeft,
    Nat.testBit_shiftRight, Nat.testBit_and, Nat.testBit_two_pow_sub_one, h1bit, ge_iff_le]
  rcases Nat.lt_trichotomy j k with hjk | hjk | hjk
  · rw [hlow j (by omega)]
    simp [hjk, show j < k + 1 by omega, show ¬ (k + 1 ≤ j) by omega,
      show ¬ (k = j) by omega, show ¬ (k + 2 ≤ j) by omega]
  · subst hjk
    rw [hlow j (le_refl _)]
    simp [show ¬ (j + 1 ≤ j) by omega, show ¬ (j + 2 ≤ j) by omega]
  · rcases Nat.lt_trichotomy j (k + 1) with hj1 | hj1 | hj1
    · omega
    · subst hj1
      simp [show ¬ (k + 2 ≤ k + 1) by omega]
    · simp [show k + 1 ≤ j by omega, show k + 2 ≤ j by omega, show ¬ (k = j) by omega,
        show ¬ (j < k + 1) by omega, show ¬ (j - (k + 1) = 0) by omega,
        show k + 2 + (j - (k + 2)) = j by omega]

/-- The exact arithmetic value of `parent`'s bit expression. -/
theorem parent_val_arith (X k : Nat) (hk : X % 2 ^ (k + 1) = 2 ^ k - 1) :
    (X ||| 2 ^ k) ^^^ ((X >>> (k + 1) &&& 1) <<< (k + 1))
      = 2 ^ (k + 2) * (X / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) := by
  have hb : 2 ^ (k + 1) - 1 < 2 ^ (k + 2) := by
    have h1 : 2 ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ 2 ^ (k + 1) := Nat.one_le_two_pow
    omega
  rw [parent_bitops_eq X k hk, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, mul_comm,
    Nat.two_pow_add_eq_or_of_lt hb]

/-- `parent`'s value as it appears after pushing the U32 `.val` through the bit ops
    (with the `% U32.size` wrap-arounds that the extracted shifts carry). -/
theorem parent_val_u32 (x : Std.U32) (k : Nat) (hk30 : k ≤ 30)
    (hkmod : (↑x : Nat) % 2 ^ (k + 1) = 2 ^ k - 1) :
    ((↑x : Nat) ||| 1 <<< k % U32.size) ^^^
      (((↑x : Nat) >>> (k + 1) &&& 1) <<< (k + 1) % U32.size)
      = 2 ^ (k + 2) * ((↑x : Nat) / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) := by
  have hsz31 : (2 : Nat) ^ 31 < U32.size := by native_decide
  have e1 : (1 : Nat) <<< k < U32.size := by
    rw [Nat.shiftLeft_eq, one_mul]
    exact lt_of_le_of_lt (Nat.pow_le_pow_right (by norm_num) (by omega)) hsz31
  have hb : ((↑x : Nat) >>> (k + 1) &&& 1) ≤ 1 := by
    have := Nat.and_one_is_mod ((↑x : Nat) >>> (k + 1)); omega
  have e2 : ((↑x : Nat) >>> (k + 1) &&& 1) <<< (k + 1) < U32.size := by
    rw [Nat.shiftLeft_eq]
    calc ((↑x : Nat) >>> (k + 1) &&& 1) * 2 ^ (k + 1)
        ≤ 1 * 2 ^ (k + 1) := Nat.mul_le_mul_right _ hb
      _ = 2 ^ (k + 1) := by ring
      _ ≤ 2 ^ 31 := Nat.pow_le_pow_right (by norm_num) (by omega)
      _ < U32.size := hsz31
  rw [Nat.mod_eq_of_lt e1, Nat.mod_eq_of_lt e2,
    show (1 : Nat) <<< k = 2 ^ k from by rw [Nat.shiftLeft_eq, one_mul]]
  exact parent_val_arith ↑x k hkmod

/-- Every natural has some clear bit (its `x`-th bit and above are all clear). -/
theorem tones_ex (x : Nat) : ∃ m, x.testBit m = false :=
  ⟨x, Nat.testBit_lt_two_pow Nat.lt_two_pow_self⟩

/-- Trailing-ones count (the mathematical value of `level`): the index of the lowest clear bit. -/
noncomputable def tones (x : Nat) : Nat := Nat.find (tones_ex x)

/-- `tones x` is the trailing-ones count: `x % 2^(tones x + 1) = 2^(tones x) − 1`. -/
theorem tones_mod (x : Nat) : x % 2 ^ (tones x + 1) = 2 ^ (tones x) - 1 := by
  set m := tones x with hm
  have hspec : x.testBit m = false := Nat.find_spec (tones_ex x)
  have hmin : ∀ j, j < m → x.testBit j = true := by
    intro j hj
    have := Nat.find_min (tones_ex x) (m := j) hj
    simpa using this
  refine Nat.eq_of_testBit_eq fun j => ?_
  rw [Nat.testBit_mod_two_pow, Nat.testBit_two_pow_sub_one]
  rcases Nat.lt_trichotomy j m with h | h | h
  · rw [hmin j h]; simp [show j < m + 1 by omega, h]
  · subst h; simp [hspec]
  · simp [show ¬ (j < m + 1) by omega, show ¬ (j < m) by omega]

/-- If two even numbers agree after a right shift by `k` but are distinct, then `k ≥ 2`:
    both have bit 0 clear, so they must differ in some bit `1 ≤ j < k`. -/
theorem even_shift_eq_ge_two {a b k : Nat} (ha : a % 2 = 0) (hb : b % 2 = 0)
    (hne : a ≠ b) (heq : a / 2 ^ k = b / 2 ^ k) : 2 ≤ k := by
  by_contra hlt
  have hk : k = 0 ∨ k = 1 := by omega
  rcases hk with h | h <;> subst h
  · simp only [pow_zero, Nat.div_one] at heq; exact hne heq
  · have hda := Nat.div_add_mod a 2
    have hdb := Nat.div_add_mod b 2
    simp only [pow_one] at heq
    omega

/-- The parent value `2^(k+2)·q + (2^(k+1)−1)` has exactly `k+1` trailing ones. -/
theorem tones_parent (k q : Nat) :
    tones (2 ^ (k + 2) * q + (2 ^ (k + 1) - 1)) = k + 1 := by
  have hlt : 2 ^ (k + 1) - 1 < 2 ^ (k + 2) := by
    have h1 : (2 : Nat) ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ (2 : Nat) ^ (k + 1) := Nat.one_le_two_pow
    omega
  have hmod : (2 ^ (k + 2) * q + (2 ^ (k + 1) - 1)) % 2 ^ ((k + 1) + 1) = 2 ^ (k + 1) - 1 := by
    rw [show (k + 1) + 1 = k + 2 from by omega, Nat.mul_add_mod, Nat.mod_eq_of_lt hlt]
  exact trailing_unique _ (tones _) (k + 1) (tones_mod _) hmod

/-- `2^d − 1` has exactly `d` trailing ones. -/
theorem tones_pow_sub_one (d : Nat) : tones (2 ^ d - 1) = d := by
  have hlt : 2 ^ d - 1 < 2 ^ (d + 1) := by
    have h1 : (2 : Nat) ^ d ≤ 2 ^ (d + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ (2 : Nat) ^ d := Nat.one_le_two_pow
    omega
  have hmod : (2 ^ d - 1) % 2 ^ (d + 1) = 2 ^ d - 1 := Nat.mod_eq_of_lt hlt
  exact trailing_unique _ (tones _) d (tones_mod _) hmod

/-- An even number has zero trailing ones. -/
theorem tones_even (n : Nat) (h : n % 2 = 0) : tones n = 0 := by
  refine trailing_unique n (tones n) 0 (tones_mod n) ?_
  simpa using h

/-- The parent value stays below `2^(d+1)` when the child does and the level `k < d`. -/
theorem parent_lt (d k q : Nat) (hkd : k < d) (hq : q < 2 ^ (d - 1 - k)) :
    2 ^ (k + 2) * q + (2 ^ (k + 1) - 1) < 2 ^ (d + 1) := by
  have hexp : (k + 2) + (d - 1 - k) = d + 1 := by omega
  have hpow : 2 ^ (k + 2) * 2 ^ (d - 1 - k) = 2 ^ (d + 1) := by rw [← pow_add, hexp]
  have hmul : 2 ^ (k + 2) * q ≤ 2 ^ (k + 2) * (2 ^ (d - 1 - k) - 1) :=
    Nat.mul_le_mul_left _ (by omega)
  have hexpand : 2 ^ (k + 2) * (2 ^ (d - 1 - k) - 1) = 2 ^ (d + 1) - 2 ^ (k + 2) := by
    rw [Nat.mul_sub, mul_one, hpow]
  have h21 : 2 ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
  have h1le : 1 ≤ (2 : Nat) ^ (k + 1) := Nat.one_le_two_pow
  have hp1 : 2 ^ (k + 2) ≤ 2 ^ (d + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

/-- A node value bounded by `2^(d+1)` with level `≤ d ≤ 30` is `< 2^31 − 1` (it can't be the
    31-trailing-ones value `2^31−1`). The per-element bound needed for `sibling` panic-freedom. -/
theorem small_of_tones (v d : Nat) (hd : d ≤ 30) (hv : v < 2 ^ (d + 1)) (ht : tones v ≤ d) :
    v < 2 ^ 31 - 1 := by
  rcases Nat.lt_or_ge d 30 with hd' | hd'
  · have h1 : (2 : Nat) ^ (d + 1) ≤ 2 ^ 30 := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : (2 : Nat) ^ 30 < 2 ^ 31 - 1 := by norm_num
    omega
  · have hd30' : d = 30 := by omega
    subst hd30'
    by_contra hc
    have hv_eq : v = 2 ^ 31 - 1 := by
      have : (2 : Nat) ^ (30 + 1) = 2 ^ 31 := by norm_num
      omega
    have htp := tones_pow_sub_one 31
    rw [← hv_eq] at htp
    omega

/-- A value `< 2^31 − 1` has at most 30 trailing ones. -/
theorem tones_le_30 (v : Nat) (hv : v < 2 ^ 31 - 1) : tones v ≤ 30 := by
  by_contra hc
  have hm := tones_mod v
  have hge : (2 : Nat) ^ 31 ≤ 2 ^ tones v := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hle : v % 2 ^ (tones v + 1) ≤ v := Nat.mod_le _ _
  rw [hm] at hle
  omega

/-- An odd number has at least one trailing one. -/
theorem tones_pos_of_odd (x : Nat) (h : x % 2 = 1) : 1 ≤ tones x := by
  by_contra hc
  have ht0 : tones x = 0 := by omega
  have hm := tones_mod x
  rw [ht0] at hm; simp at hm; omega

/-- The parent value of a node `< 2^31` (level `≤ 30`) stays `< 2^31` (no carry past bit 31). -/
theorem parent_val_lt (v : Nat) (hv : v < 2 ^ 31) (hk : tones v ≤ 30) :
    2 ^ (tones v + 2) * (v / 2 ^ (tones v + 2)) + (2 ^ (tones v + 1) - 1) < 2 ^ 31 := by
  rcases Nat.lt_or_ge (tones v) 30 with hlt | hge
  · refine parent_lt 30 (tones v) (v / 2 ^ (tones v + 2)) hlt ?_
    refine Nat.div_lt_of_lt_mul ?_
    rw [← pow_add, show (tones v + 2) + (30 - 1 - tones v) = 31 from by omega]
    exact hv
  · have hk30 : tones v = 30 := by omega
    rw [hk30]
    have hq0 : v / 2 ^ (30 + 2) = 0 := by
      apply Nat.div_eq_of_lt
      have : (2 : Nat) ^ 31 ≤ 2 ^ (30 + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
      omega
    rw [hq0, Nat.mul_zero, Nat.zero_add]
    have h2 : (2 : Nat) ^ (30 + 1) = 2 ^ 31 := by norm_num
    have h1 : 1 ≤ (2 : Nat) ^ (30 + 1) := Nat.one_le_two_pow
    omega

end openmls
