-- [openmls]: PROVED `@[spec]` contracts for standard-library `core`/`alloc` operations.
-- These fill in specs that the extraction did not provide, but — unlike the contracts in
-- `AdmittedCoreSpecs.lean` — they are *discharged here* (no `sorry`), so they are NOT part of the
-- trusted audit surface. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-- `Vec::len` returns the vec's length. -/
@[spec]
theorem vec_len_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.len v
    ⦃ ⇓ n => ⌜ (↑n : Nat) = vecLen v ⌝ ⦄ := by
  unfold alloc.vec.Vec.len vecLen CoreModels.rust_primitives.sequence.seq_len
  mvcgen

/-- `Vec::new` returns an empty vec. -/
@[spec]
theorem vec_new_spec (T : Type) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.new T
    ⦃ ⇓ v => ⌜ vecLen v = 0 ∧ v.1.val = [] ⌝ ⦄ := by
  unfold alloc.vec.Vec.new alloc.vec.VecTGlobal.new vecLen
  mvcgen

/-- `Vec::with_capacity` returns an empty vec. -/
@[spec]
theorem vec_with_capacity_spec (T : Type) (c : Std.Usize) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.with_capacity T c
    ⦃ ⇓ v => ⌜ vecLen v = 0 ⌝ ⦄ := by
  unfold alloc.vec.Vec.with_capacity alloc.vec.VecTGlobal.with_capacity
    alloc.vec.VecTGlobal.new vecLen
  mvcgen

end openmls
