-- [openmls]: the TRUSTED audit surface (concern C, admitted).
--
-- Every `sorry` a reviewer must trust to believe the treemath panic-freedom development lives here,
-- and nowhere else. They are all of one kind: `@[spec]` contracts for the `core`/`alloc` operations
-- whose bodies Charon could not extract, and which therefore appear as bare `axiom`s in
-- `FunsExternal.lean`. Each contract states a standard, total Rust operation's faithful semantics
-- and is *admitted* — REVIEW CAREFULLY.
--
-- Nothing else in this file is trusted: the model the contracts are phrased over (`sliceIterElems`,
-- now in `Common.lean`) is a *real definition*, not an opaque. The proved counterparts of such
-- specs live in `MissingCoreSpecs.lean`; the mathematical content that consumes these contracts is
-- proved in `Proofs.lean`. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-! ### Trusted `@[spec]` contracts for iterator combinators

   `Iterator::collect` (and the `map`-then-`collect` pipelines built on it) is an opaque `axiom` in
   `FunsExternal.lean`; the `@[spec]` contracts below state their faithful Rust semantics and are
   *admitted* (trusted — REVIEW). The mathematical content (per-element `sibling` panic-freedom,
   `copath_loop`'s accumulation) is proved in `Proofs.lean`. `Vec::{is_empty, pop, append, push}`,
   `<Vec<T> as Index<usize>>::index`, the slice `deref`/`iter`/`reverse`, `deref_mut`, `min`,
   `<u32 as Ord>::cmp`, `div_ceil`, and `Iterator::{map, all}` all used to live here; they now have
   PROVED specs in `MissingCoreSpecs.lean`, since `CoreModels`/`FunsExternal` supply concrete bodies
   for them. The two `collect` contracts below are the ONLY admitted contracts left in this file. -/

/-- TRUSTED: collecting a pure, state-preserving closure mapped over a slice iterator yields
    exactly the mapped element list. -/
theorem slice_iter_map_collect_spec {T O F : Type}
    (inst : core.ops.function.FnMut F T O) (iter : core.slice.iter.Iter T) (f : F) (g : T → O)
    (hcall : ∀ e ∈ sliceIterElems iter, inst.call_mut f e = ok (g e, f)) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let m ← core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map inst iter f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT T) inst
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator O) m)
    ⦃ ⇓ v => ⌜ v.1 = (sliceIterElems iter).map g ⌝ ⦄ := by sorry

/-- TRUSTED: collecting a closure `f` over a vec via `into_iter`/`map`/`collect` is panic-free when
    `f` is panic-free on every element. Generic over the element type and closure — purely a `core`
    contract. The `sibling` instance used by `copath` is *derived* (not admitted) in `Proofs.lean`. -/
theorem into_map_collect_spec {T : Type} (v : alloc.vec.Vec T) (f : T → Result T)
    (hsafe : ∀ e ∈ v.1, ⦃ ⌜ True ⌝ ⦄ f e ⦃ ⇓ _ => ⌜ True ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let ii ← alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter v
      let m ← alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
          (BuiltinFnMut T T) ii f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator T)
        (BuiltinFnMut T T)
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator T) m)
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by sorry

end openmls
