-- [openmls]: the TRUSTED audit surface (concern C, admitted).
--
-- Every `sorry` a reviewer must trust to believe the treemath panic-freedom development lives here
-- (and nowhere else): `@[spec]` contracts for `core`/`alloc` operations that Charon could not
-- extract (declared as bare `axiom`s in `FunsExternal.lean`), plus nothing else — the
-- model they are phrased over (`sliceIterElems`) is now a *real definition*, not an opaque.
-- Each contract states a standard, total Rust
-- operation's faithful semantics and is *admitted* — REVIEW CAREFULLY. The proved counterparts of
-- such specs live in `MissingCoreSpecs.lean`; the mathematical content that consumes these contracts
-- is proved in `Proofs.lean`. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-! ### The model the trusted iterator contracts are phrased over -/

/-- A slice iterator's remaining elements. **Not trusted**: `CoreModels`' `core.slice.iter.Iter T`
    is `@[reducible]`-equal to `rust_primitives.sequence.Seq T = Aeneas.Std.Slice T`, a subtype of
    `List T`, so the remaining elements are literally the underlying list. (This used to be an
    `opaque`; the new extraction made the iterator type concrete, so it is a real definition and
    the trusted surface shrank accordingly.) -/
def sliceIterElems {T : Type} (it : core.slice.iter.Iter T) : List T := it.val

/-! ### Trusted `@[spec]` contracts for `Vec`/slice operations

   The Rust standard-library operations below are declared as bare `axiom`s in `FunsExternal.lean`
   because Charon could not extract their bodies. The `@[spec]` lemmas state their faithful Rust
   semantics; they are *admitted* (`sorry`). Each is a standard, total operation: `deref_mut`
   exposes a `Vec`'s contents as a slice with an identity write-back; `reverse` reverses the slice;
   indexing is safe within bounds; `min` returns a value bounded by both arguments. -/

/-- `<Vec<T> as DerefMut>::deref_mut` never fails and returns the slice view together with a
    write-back closure. A `&mut [T]` view can reorder/overwrite elements but *cannot resize*, so
    writing back **any** resulting slice yields a vec of the original length: `vecLen (back s') =
    vecLen v` for all `s'`. (The slice itself is opaque here — `core.slice.Slice T` reduces to `T`
    in `CoreModels` — so the usable content lives in the write-back.) Trusted: `deref_mut` is a bare
    `axiom` in `FunsExternal.lean`.
    Not `@[spec]`: it's stepped explicitly via `mvcgen [deref_mut_slice_spec]`, because the
    extracted `let (s, back) ← deref_mut …` is a *tuple-destructuring* bind. `mvcgen` introduces
    the result as one opaque variable and leaves `let (s, back) := r` (the bind's `match` on the
    result) unreduced — independent of this postcondition's shape — so the caller turns `r` into a
    constructor (`casesm* _ × _`) and `simp`s to reduce it. -/
@[spec]
theorem deref_mut_slice_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut v
    ⦃ ⇓ ⟨_, back⟩ => ⌜ ∀ s', vecLen (back s') = vecLen v ⌝ ⦄ := by
  sorry

/-- `<[T]>::reverse` never fails. -/
@[spec]
theorem reverse_slice_spec {T : Type} (s : Slice T) :
    ⦃ ⌜ True ⌝ ⦄
    core.slice.Slice.reverse s
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  sorry

/-- `<Vec<T> as Index<usize>>::index`: succeeds (no out-of-bounds panic) when the
    index is within the vec's length. -/
@[spec]
theorem vec_index_spec {T Output : Type}
    (inst : core.slice.index.SliceIndex Std.Usize (Slice T) Output)
    (v : alloc.vec.Vec T) (i : Std.Usize) :
    ⦃ ⌜ (↑i : Nat) < vecLen v ⌝ ⦄
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index inst v i
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  sorry

/-- `Vec::push` grows the length by one and appends `x` (panic-free below the size ceiling). -/
@[spec]
theorem vec_push_spec {T : Type} (v : alloc.vec.Vec T) (x : T) :
    ⦃ ⌜ vecLen v < Std.Usize.max ⌝ ⦄
    alloc.vec.Vec.push v x
    ⦃ ⇓ v' => ⌜ vecLen v' = vecLen v + 1 ∧ v'.1 = v.1 ++ [x] ⌝ ⦄ := by
  -- TODO: provable from the `seq_push` definition; admitted for now (mvcgen vs. dependent-`if`).
  sorry

/-- `core::cmp::min` for `usize`: returns a value bounded above by both arguments. -/
@[spec]
theorem min_usize_spec (a b : Std.Usize) :
    ⦃ ⌜ True ⌝ ⦄
    core.cmp.min core.Usize.Insts.CoreCmpOrd a b
    ⦃ ⇓ m => ⌜ (↑m : Nat) ≤ ↑a ∧ (↑m : Nat) ≤ ↑b ⌝ ⦄ := by
  sorry

/-- `<u32 as Ord>::cmp` is panic-free (trusted: total comparison). -/
@[spec]
theorem u32_cmp_spec (a b : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄ core.U32.Insts.CoreCmpOrd.cmp a b ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  sorry

/-- `u32::div_ceil x y = ⌈x/y⌉`, computed as `(x + y - 1) / y`, panic-free exactly when the
    divisor is nonzero (Rust panics on division by zero). Trusted: `div_ceil` is a bare `axiom`
    in `FunsExternal.lean` (Charon could not extract its body). -/
@[spec]
theorem u32_div_ceil_spec (x y : Std.U32) :
    ⦃ ⌜ 0 < (↑y : Nat) ⌝ ⦄
    core.num.U32.div_ceil x y
    ⦃ ⇓ r => ⌜ (↑r : Nat) = (↑x + ↑y - 1) / ↑y ⌝ ⦄ := by
  sorry

/-! ### Trusted `@[spec]` contracts for iterator combinators

   The iterator combinators (`map`/`collect`/`all`) are opaque `axiom`s in `FunsExternal.lean`;
   the `@[spec]` contracts below state their faithful Rust semantics and are *admitted* (trusted —
   REVIEW). The mathematical content (per-element `sibling` panic-freedom, `copath_loop`'s
   accumulation) is proved in `Proofs.lean`. `Vec::{is_empty, pop, append}` and the slice
   `deref`/`iter` used to live here; they now have PROVED specs in `MissingCoreSpecs.lean`, since
   `CoreModels` supplies concrete bodies for them. -/

/-- TRUSTED: slice-iter `Iterator::all` returns the conjunction of the (pure, state-preserving)
    predicate over the remaining elements. -/
@[spec]
theorem slice_iter_all_spec {T F : Type}
    (inst : core.ops.function.FnMut F T Bool) (iter : core.slice.iter.Iter T) (f : F)
    (P : T → Bool)
    (hcall : ∀ e ∈ sliceIterElems iter, inst.call_mut f e = ok (P e, f)) :
    ⦃ ⌜ True ⌝ ⦄
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all inst iter f
    ⦃ ⇓ r => ⌜ r.1 = (sliceIterElems iter).all P ⌝ ⦄ := by sorry

/-- TRUSTED: collecting a pure, state-preserving closure mapped over a slice iterator yields
    exactly the mapped element list. -/
theorem slice_iter_map_collect_spec {T O F : Type}
    (inst : core.ops.function.FnMut F T O) (iter : core.slice.iter.Iter T) (f : F) (g : T → O)
    (hcall : ∀ e ∈ sliceIterElems iter, inst.call_mut f e = ok (g e, f)) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let m ← core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map inst iter f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT T) inst
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator O) m)
    ⦃ ⇓ v => ⌜ v.1 = (sliceIterElems iter).map g ⌝ ⦄ := by sorry

/-- TRUSTED: collecting a closure `f` over a vec via `into_iter`/`map`/`collect` is panic-free when
    `f` is panic-free on every element. Generic over the element type and closure — purely a `core`
    contract. The `sibling` instance used by `copath` is *derived* (not admitted) in `Proofs.lean`. -/
theorem into_map_collect_spec {T : Type} (v : alloc.vec.Vec T) (f : T → Result T)
    (hsafe : ∀ e ∈ v.1, ⦃ ⌜ True ⌝ ⦄ f e ⦃ ⇓ _ => ⌜ True ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let ii ← alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter v
      let m ← alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
          (BuiltinFnMut T T) ii f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator T)
        (BuiltinFnMut T T)
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator T) m)
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by sorry

end openmls
