-- [openmls]: pure-`Nat` / bit-arithmetic lemmas (concern B).
-- No monad, no Aeneas `Result` — just the trailing-ones count `tones` and the `parent` bit-expression
-- arithmetic underpinning the treemath value specs. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-- `1 <<< k` (as `u32`) is nonzero whenever the shift amount is in range. -/
theorem one_le_one_shiftLeft_mod (k : Nat) (h : k < 32) :
    1 ≤ 1 <<< k % Aeneas.Std.U32.size := by
  have e : 1 <<< k = 2 ^ k := by simp [Nat.shiftLeft_eq]
  have h2 : (2 : Nat) ^ 31 < Aeneas.Std.U32.size := by simp [Aeneas.Std.U32.size_eq]
  have hle : (2 : Nat) ^ k ≤ 2 ^ 31 := Nat.pow_le_pow_right (by norm_num) (by omega)
  rw [e, Nat.mod_eq_of_lt (by omega)]
  exact Nat.one_le_two_pow

/-- `(2^k − 1) mod 2^j = 2^j − 1` when `j ≤ k` (the low `j` bits of `2^k−1` are all 1). -/
theorem pow_sub_one_mod (j k : Nat) (h : j ≤ k) :
    (2 ^ k - 1) % 2 ^ j = 2 ^ j - 1 := by
  have hjk : 2 ^ j * 2 ^ (k - j) = 2 ^ k := by rw [← pow_add]; congr 1; omega
  have hjle : 2 ^ j ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) h
  have hj1 : 1 ≤ 2 ^ j := Nat.one_le_two_pow
  have e : 2 ^ k - 1 = 2 ^ j * (2 ^ (k - j) - 1) + (2 ^ j - 1) := by
    rw [Nat.mul_sub, mul_one, hjk]; omega
  rw [e, Nat.mul_add_mod, Nat.mod_eq_of_lt (by omega)]

/-- The trailing-ones count `m` with `a % 2^(m+1) = 2^m − 1` is unique. -/
theorem trailing_unique (a m n : Nat)
    (hm : a % 2 ^ (m + 1) = 2 ^ m - 1)
    (hn : a % 2 ^ (n + 1) = 2 ^ n - 1) : m = n := by
  rcases Nat.lt_trichotomy m n with h | h | h
  · exfalso
    have hdvd : 2 ^ (m + 1) ∣ 2 ^ (n + 1) := pow_dvd_pow 2 (by omega)
    have := Nat.mod_mod_of_dvd a hdvd
    rw [hn, pow_sub_one_mod (m + 1) n (by omega)] at this
    rw [hm] at this
    have : (2:Nat) ^ m < 2 ^ (m + 1) := Nat.pow_lt_pow_right (by norm_num) (by omega)
    have : 1 ≤ (2:Nat) ^ m := Nat.one_le_two_pow
    omega
  · exact h
  · exfalso
    have hdvd : 2 ^ (n + 1) ∣ 2 ^ (m + 1) := pow_dvd_pow 2 (by omega)
    have := Nat.mod_mod_of_dvd a hdvd
    rw [hm, pow_sub_one_mod (n + 1) m (by omega)] at this
    rw [hn] at this
    have : (2:Nat) ^ n < 2 ^ (n + 1) := Nat.pow_lt_pow_right (by norm_num) (by omega)
    have : 1 ≤ (2:Nat) ^ n := Nat.one_le_two_pow
    omega

/-- `parent`'s bit expression equals a pure high/low OR split of `X`. -/
theorem parent_bitops_eq (X k : Nat) (hk : X % 2 ^ (k + 1) = 2 ^ k - 1) :
    (X ||| 2 ^ k) ^^^ ((X >>> (k + 1) &&& 1) <<< (k + 1))
      = ((X >>> (k + 2)) <<< (k + 2)) ||| (2 ^ (k + 1) - 1) := by
  have h1bit : ∀ m, (1:Nat).testBit m = decide (m = 0) := by
    intro m; rw [show (1:Nat) = 2 ^ 0 from rfl, Nat.testBit_two_pow]; simp [eq_comm]
  have hlow : ∀ j, j ≤ k → X.testBit j = decide (j < k) := by
    intro j hj
    have h1 := Nat.testBit_mod_two_pow X (k + 1) j
    rw [hk, Nat.testBit_two_pow_sub_one] at h1
    have hj1 : j < k + 1 := by omega
    simp only [hj1, decide_true, Bool.true_and] at h1
    exact h1.symm
  refine Nat.eq_of_testBit_eq fun j => ?_
  simp only [Nat.testBit_lor, Nat.testBit_xor, Nat.testBit_two_pow, Nat.testBit_shiftLeft,
    Nat.testBit_shiftRight, Nat.testBit_and, Nat.testBit_two_pow_sub_one, h1bit, ge_iff_le]
  rcases Nat.lt_trichotomy j k with hjk | hjk | hjk
  · rw [hlow j (by omega)]
    simp [hjk, show j < k + 1 by omega, show ¬ (k + 1 ≤ j) by omega,
      show ¬ (k = j) by omega, show ¬ (k + 2 ≤ j) by omega]
  · subst hjk
    rw [hlow j (le_refl _)]
    simp [show ¬ (j + 1 ≤ j) by omega, show ¬ (j + 2 ≤ j) by omega]
  · rcases Nat.lt_trichotomy j (k + 1) with hj1 | hj1 | hj1
    · omega
    · subst hj1
      simp [show ¬ (k + 2 ≤ k + 1) by omega]
    · simp [show k + 1 ≤ j by omega, show k + 2 ≤ j by omega, show ¬ (k = j) by omega,
        show ¬ (j < k + 1) by omega, show ¬ (j - (k + 1) = 0) by omega,
        show k + 2 + (j - (k + 2)) = j by omega]

/-- The exact arithmetic value of `parent`'s bit expression. -/
theorem parent_val_arith (X k : Nat) (hk : X % 2 ^ (k + 1) = 2 ^ k - 1) :
    (X ||| 2 ^ k) ^^^ ((X >>> (k + 1) &&& 1) <<< (k + 1))
      = 2 ^ (k + 2) * (X / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) := by
  have hb : 2 ^ (k + 1) - 1 < 2 ^ (k + 2) := by
    have h1 : 2 ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ 2 ^ (k + 1) := Nat.one_le_two_pow
    omega
  rw [parent_bitops_eq X k hk, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, mul_comm,
    Nat.two_pow_add_eq_or_of_lt hb]

/-- `parent`'s value as it appears after pushing the U32 `.val` through the bit ops
    (with the `% U32.size` wrap-arounds that the extracted shifts carry). -/
theorem parent_val_u32 (x : Std.U32) (k : Nat) (hk30 : k ≤ 30)
    (hkmod : (↑x : Nat) % 2 ^ (k + 1) = 2 ^ k - 1) :
    ((↑x : Nat) ||| 1 <<< k % U32.size) ^^^
      (((↑x : Nat) >>> (k + 1) &&& 1) <<< (k + 1) % U32.size)
      = 2 ^ (k + 2) * ((↑x : Nat) / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) := by
  have hsz31 : (2 : Nat) ^ 31 < U32.size := by simp [Aeneas.Std.U32.size_eq]
  have e1 : (1 : Nat) <<< k < U32.size := by
    rw [Nat.shiftLeft_eq, one_mul]
    exact lt_of_le_of_lt (Nat.pow_le_pow_right (by norm_num) (by omega)) hsz31
  have hb : ((↑x : Nat) >>> (k + 1) &&& 1) ≤ 1 := by
    have := Nat.and_one_is_mod ((↑x : Nat) >>> (k + 1)); omega
  have e2 : ((↑x : Nat) >>> (k + 1) &&& 1) <<< (k + 1) < U32.size := by
    rw [Nat.shiftLeft_eq]
    calc ((↑x : Nat) >>> (k + 1) &&& 1) * 2 ^ (k + 1)
        ≤ 1 * 2 ^ (k + 1) := Nat.mul_le_mul_right _ hb
      _ = 2 ^ (k + 1) := by ring
      _ ≤ 2 ^ 31 := Nat.pow_le_pow_right (by norm_num) (by omega)
      _ < U32.size := hsz31
  rw [Nat.mod_eq_of_lt e1, Nat.mod_eq_of_lt e2,
    show (1 : Nat) <<< k = 2 ^ k from by rw [Nat.shiftLeft_eq, one_mul]]
  exact parent_val_arith ↑x k hkmod

/-- Every natural has some clear bit (its `x`-th bit and above are all clear). -/
theorem tones_ex (x : Nat) : ∃ m, x.testBit m = false :=
  ⟨x, Nat.testBit_lt_two_pow Nat.lt_two_pow_self⟩

/-- Trailing-ones count (the mathematical value of `level`): the index of the lowest clear bit. -/
noncomputable def tones (x : Nat) : Nat := Nat.find (tones_ex x)

/-- `tones x` is the trailing-ones count: `x % 2^(tones x + 1) = 2^(tones x) − 1`. -/
theorem tones_mod (x : Nat) : x % 2 ^ (tones x + 1) = 2 ^ (tones x) - 1 := by
  set m := tones x with hm
  have hspec : x.testBit m = false := Nat.find_spec (tones_ex x)
  have hmin : ∀ j, j < m → x.testBit j = true := by
    intro j hj
    have := Nat.find_min (tones_ex x) (m := j) hj
    simpa using this
  refine Nat.eq_of_testBit_eq fun j => ?_
  rw [Nat.testBit_mod_two_pow, Nat.testBit_two_pow_sub_one]
  rcases Nat.lt_trichotomy j m with h | h | h
  · rw [hmin j h]; simp [show j < m + 1 by omega, h]
  · subst h; simp [hspec]
  · simp [show ¬ (j < m + 1) by omega, show ¬ (j < m) by omega]

/-- If two even numbers agree after a right shift by `k` but are distinct, then `k ≥ 2`:
    both have bit 0 clear, so they must differ in some bit `1 ≤ j < k`. -/
theorem even_shift_eq_ge_two {a b k : Nat} (ha : a % 2 = 0) (hb : b % 2 = 0)
    (hne : a ≠ b) (heq : a / 2 ^ k = b / 2 ^ k) : 2 ≤ k := by
  by_contra hlt
  have hk : k = 0 ∨ k = 1 := by omega
  rcases hk with h | h <;> subst h
  · simp only [pow_zero, Nat.div_one] at heq; exact hne heq
  · have hda := Nat.div_add_mod a 2
    have hdb := Nat.div_add_mod b 2
    simp only [pow_one] at heq
    omega

/-- The parent value `2^(k+2)·q + (2^(k+1)−1)` has exactly `k+1` trailing ones. -/
theorem tones_parent (k q : Nat) :
    tones (2 ^ (k + 2) * q + (2 ^ (k + 1) - 1)) = k + 1 := by
  have hlt : 2 ^ (k + 1) - 1 < 2 ^ (k + 2) := by
    have h1 : (2 : Nat) ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ (2 : Nat) ^ (k + 1) := Nat.one_le_two_pow
    omega
  have hmod : (2 ^ (k + 2) * q + (2 ^ (k + 1) - 1)) % 2 ^ ((k + 1) + 1) = 2 ^ (k + 1) - 1 := by
    rw [show (k + 1) + 1 = k + 2 from by omega, Nat.mul_add_mod, Nat.mod_eq_of_lt hlt]
  exact trailing_unique _ (tones _) (k + 1) (tones_mod _) hmod

/-- `2^d − 1` has exactly `d` trailing ones. -/
theorem tones_pow_sub_one (d : Nat) : tones (2 ^ d - 1) = d := by
  have hlt : 2 ^ d - 1 < 2 ^ (d + 1) := by
    have h1 : (2 : Nat) ^ d ≤ 2 ^ (d + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h2 : 1 ≤ (2 : Nat) ^ d := Nat.one_le_two_pow
    omega
  have hmod : (2 ^ d - 1) % 2 ^ (d + 1) = 2 ^ d - 1 := Nat.mod_eq_of_lt hlt
  exact trailing_unique _ (tones _) d (tones_mod _) hmod

/-- An even number has zero trailing ones. -/
theorem tones_even (n : Nat) (h : n % 2 = 0) : tones n = 0 := by
  refine trailing_unique n (tones n) 0 (tones_mod n) ?_
  simpa using h

/-- The parent value stays below `2^(d+1)` when the child does and the level `k < d`. -/
theorem parent_lt (d k q : Nat) (hkd : k < d) (hq : q < 2 ^ (d - 1 - k)) :
    2 ^ (k + 2) * q + (2 ^ (k + 1) - 1) < 2 ^ (d + 1) := by
  have hexp : (k + 2) + (d - 1 - k) = d + 1 := by omega
  have hpow : 2 ^ (k + 2) * 2 ^ (d - 1 - k) = 2 ^ (d + 1) := by rw [← pow_add, hexp]
  have hmul : 2 ^ (k + 2) * q ≤ 2 ^ (k + 2) * (2 ^ (d - 1 - k) - 1) :=
    Nat.mul_le_mul_left _ (by omega)
  have hexpand : 2 ^ (k + 2) * (2 ^ (d - 1 - k) - 1) = 2 ^ (d + 1) - 2 ^ (k + 2) := by
    rw [Nat.mul_sub, mul_one, hpow]
  have h21 : 2 ^ (k + 1) ≤ 2 ^ (k + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
  have h1le : 1 ≤ (2 : Nat) ^ (k + 1) := Nat.one_le_two_pow
  have hp1 : 2 ^ (k + 2) ≤ 2 ^ (d + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

/-- A value `< 2^31 − 1` has at most 30 trailing ones. -/
theorem tones_le_30 (v : Nat) (hv : v < 2 ^ 31 - 1) : tones v ≤ 30 := by
  by_contra hc
  have hm := tones_mod v
  have hge : (2 : Nat) ^ 31 ≤ 2 ^ tones v := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hle : v % 2 ^ (tones v + 1) ≤ v := Nat.mod_le _ _
  rw [hm] at hle
  omega

/-! ### `U32`-level shift/mask helpers -/

/-- Powers of two up to `2^31` fit in a `u32` (the `u32::pow` side condition shape). -/
theorem two_pow_le_u32_max (m : Nat) (h : m ≤ 31) : 2 ^ m ≤ Aeneas.Std.U32.max := by
  have h1 : (2 : Nat) ^ m ≤ 2 ^ 31 := Nat.pow_le_pow_right (by norm_num) h
  have h2 : (2 : Nat) ^ 31 ≤ Aeneas.Std.U32.max := by simp [Aeneas.Std.U32.max_eq]
  omega

/-- `1 <<< k % U32.size = 2^k` for `k < 32` (the shift doesn't wrap). -/
theorem one_shiftLeft_mod_eq (k : Nat) (h : k < 32) :
    1 <<< k % Aeneas.Std.U32.size = 2 ^ k := by
  simp only [Nat.one_shiftLeft]; simp_scalar

/-- Bit 0 clear ⇔ even. `@[simp]` so `simp_all!` turns the extracted `v &&& 1#u32 = 0#u32`
    low-bit guards into `↑v % 2 = 0`. -/
@[simp] theorem u32_and_one_eq_zero (v : Std.U32) :
    (v &&& 1#u32 = 0#u32) ↔ (↑v : Nat) % 2 = 0 := by
  have hval : (↑(v &&& 1#u32) : Nat) = (↑v : Nat) % 2 := by
    rw [Aeneas.Std.UScalar.val_and, show (↑(1#u32) : Nat) = 1 from rfl, Nat.and_one_is_mod]
  constructor
  · intro h; rw [h] at hval; simpa using hval.symm
  · intro h
    have hz : (↑(v &&& 1#u32) : Nat) = 0 := by rw [hval, h]
    scalar_tac

/-- From the trailing-ones characterization, `k ≥ 1` or `x` even. `@[scalar_tac]` so it fires on the
    char hypothesis: with `x` odd it discharges the `level x > 0` massert in `left`/`right`. -/
@[scalar_tac x % 2 ^ (k + 1) = 2 ^ k - 1]
theorem level_ge_one (x k : Nat) (hchar : x % 2 ^ (k + 1) = 2 ^ k - 1) :
    1 ≤ k ∨ x % 2 = 0 := by
  rcases Nat.eq_zero_or_pos k with hk | hk
  · right; subst hk; simpa using hchar
  · left; omega

/-- `level_ge_one` for the `simp`-flipped orientation (`2^k − 1` on the left). -/
@[scalar_tac 2 ^ k - 1 = x % 2 ^ (k + 1)]
theorem level_ge_one' (x k : Nat) (hchar : 2 ^ k - 1 = x % 2 ^ (k + 1)) :
    1 ≤ k ∨ x % 2 = 0 := level_ge_one x k hchar.symm

/-- `Nat.log 2 (2^(k+1) − 1) = k`: an all-ones value of width `k+1` has log₂ exactly `k`.
    This is the fixpoint fact behind `TreeSize.valid` (`s = 2^(log2 s + 1) − 1`). -/
theorem log2_two_pow_sub_one (k : Nat) : Nat.log 2 (2 ^ (k + 1) - 1) = k := by
  have hk : (1:Nat) ≤ 2 ^ k := Nat.one_le_two_pow
  have hsucc : (2:Nat) ^ (k + 1) = 2 * 2 ^ k := by rw [pow_succ]; ring
  exact Nat.log_eq_of_pow_le_of_lt_pow (by omega) (by omega)

/-! ### Registered forward rules for the `Nat.log` / shift residue

`TreeSize`-flavoured obligations leave two nonlinear atoms (`Nat.log 2 s` and `2 ^ e`) in otherwise
linear goals.  The idiom below hands `scalar_tac` their bounds as UNCONDITIONAL disjunctions (as
`level_ge_one` does): the rule fires on the pattern with no side goal, and `omega` kills the wrong
disjunct from the surrounding linear facts — so no hand-written preamble is needed. -/

/-- `log₂ x ≤ 30` unless `x` exceeds `MAX_TREE_SIZE = 2^30`.  Registered on the `Nat.log` pattern,
    so `s ≤ 2^30` in context yields the exponent bound every `TreeSize` computation needs. -/
@[scalar_tac Nat.log 2 x]
theorem log2_le_30_or (x : Nat) : Nat.log 2 x ≤ 30 ∨ 2 ^ 30 < x := by
  by_cases h : x < 2 ^ 31
  · left
    rcases Nat.eq_zero_or_pos x with hx | hx
    · simp [hx]
    · have := Nat.log_lt_of_lt_pow (show x ≠ 0 by omega) h
      omega
  · right
    have h31 : (2:Nat) ^ 30 < 2 ^ 31 := by norm_num
    omega

/-- A `u32` `1 <<< k` is zero exactly when the shift amount is out of range.  Unconditional `iff`,
    hence safe as `@[simp]`: it reduces the `h_fail` obligations of `1#u32 <<< log2 size` to the
    linear `32 ≤ k`.  Needed because `scalar_tac` is unusable on those goals — its `simp`
    preprocessing hits `maxRecDepth` on a symbolic `↑r = 2 ^ ↑e` hypothesis. -/
@[simp] theorem one_shiftLeft_mod_eq_zero_iff (k : Nat) :
    1 <<< k % Aeneas.Std.U32.size = 0 ↔ 32 ≤ k := by
  have hsz : Aeneas.Std.U32.size = 2 ^ 32 := by exact Aeneas.Std.U32.size_eq
  have e : 1 <<< k = 2 ^ k := by simp [Nat.shiftLeft_eq]
  rw [e, hsz]
  constructor
  · intro h
    by_contra hlt
    have hb : (2:Nat) ^ k < 2 ^ 32 := Nat.pow_lt_pow_right (by norm_num) (by omega)
    have h1 : (1:Nat) ≤ 2 ^ k := Nat.one_le_two_pow
    rw [Nat.mod_eq_of_lt hb] at h
    omega
  · intro h
    obtain ⟨j, hj⟩ : ∃ j, k = 32 + j := ⟨k - 32, by omega⟩
    subst hj
    rw [pow_add]
    exact Nat.mul_mod_right _ _

/-- Unconditional form of `one_le_one_shiftLeft_mod`, registered on the shift-mod pattern: a `u32`
    `1 <<< k` is nonzero unless the shift amount is out of range.  Discharges the `h_fail` branches
    of `1#u32 <<< log2 size` (where `k = 31 - m ≤ 31` holds by truncated subtraction alone). -/
@[scalar_tac 1 <<< k % Aeneas.Std.U32.size]
theorem one_le_one_shiftLeft_mod_or (k : Nat) :
    1 ≤ 1 <<< k % Aeneas.Std.U32.size ∨ 32 ≤ k := by
  by_cases h : k < 32
  · exact Or.inl (one_le_one_shiftLeft_mod k h)
  · exact Or.inr (by omega)

/-- `2 ^ e ≤ u32::MAX` unless the exponent exceeds `31`.  Disjunctive (`scalar_tac`-shaped) form of
    `two_pow_le_u32_max`, for manual use.

    NOT REGISTERED: `@[scalar_tac 2 ^ e]` was tried and REVERTED — the pattern matches nearly every
    power here, and the extra disjunction per occurrence blows up `omega`'s case split, regressing
    green goals (it broke `left.spec.proof`). -/
theorem two_pow_le_u32_max_or (e : Nat) : 2 ^ e ≤ Aeneas.Std.U32.max ∨ 31 < e := by
  by_cases h : e ≤ 31
  · exact Or.inl (two_pow_le_u32_max e h)
  · exact Or.inr (by omega)

/-! ### `bvify` bridges for the `1 <<< j` shift residue

`bvify 32` (hence `bv_tac 32`) cannot lift the extracted shift residue
`BitVec.ofNat 32 (1 <<< ↑j % UScalar.size UScalarTy.U32)` (`j : Usize`): the unconditional lift is
FALSE at `↑j = 2 ^ 32`, where the left side is `0#32` but `1#32 <<< BitVec.ofNat 32 (2 ^ 32) = 1#32`.
A conditional `@[bvify]` registration would be dead weight too — `bvify`'s discharger runs at
`maxDischargeDepth 0` and could never prove `↑j < 32`.  Hence the by-hand bridge below. -/

/-- Conditional lift of the raw `ofNat` shift residue, shaped for consumers: `hr1` is the `mvcgen`
    binding of the extracted `1u32 << level` step, and the conclusion is a `BitVec 32` equation
    whose shift amount is a *`BitVec 32` term* (`BitVec.setWidth 32 j.bv`) — natively blastable,
    unlike a `Nat`-indexed amount.  Use immediately before `bv_decide` / `bv_tac 32`:
    `have hbv := bv_of_one_shiftLeft_mod _ _ (by scalar_tac) (by assumption); bv_tac 32`.
    Not `@[bvify]`; see the section note. -/
theorem bv_of_one_shiftLeft_mod (r1 : Std.U32) (j : Std.Usize) (h : (↑j : Nat) < 32)
    (hr1 : (↑r1 : Nat) = 1 <<< (↑j : Nat) % UScalar.size UScalarTy.U32) :
    r1.bv = 1#32 <<< BitVec.setWidth 32 j.bv := by
  have hjv : j.bv.toNat = (↑j : Nat) := rfl
  have hj : (↑j : Nat) % 4294967296 = (↑j : Nat) := Nat.mod_eq_of_lt (by omega)
  have hlt : (2:Nat) ^ (↑j : Nat) < 2 ^ 32 := Nat.pow_lt_pow_right (by norm_num) h
  have hp : (2:Nat) ^ (↑j : Nat) % 4294967296 = 2 ^ (↑j : Nat) := by
    apply Nat.mod_eq_of_lt; norm_num at hlt; omega
  apply BitVec.eq_of_toNat_eq
  rw [show r1.bv.toNat = (↑r1 : Nat) from rfl, hr1, UScalar.size_UScalarTyU32,
    one_shiftLeft_mod_eq _ h]
  simp [BitVec.toNat_shiftLeft, BitVec.toNat_setWidth, hjv, hj, Nat.shiftLeft_eq, hp]

/-- `bvify` lift of a halving applied to a `U32` *value*: `↑a / 2` becomes `a.bv >>> 1`.

    Unconditionally true (the `% 2 ^ 32` truncation is the identity since `↑a < 2 ^ 32`), hence safe
    as `@[bvify]`.  The `U32`-argument form is ESSENTIAL: the generalization to arbitrary `x : Nat`
    is FALSE (`(x % 2 ^ 32) / 2 ≠ (x / 2) % 2 ^ 32` once `x ≥ 2 ^ 32`), which is why `bvify` ships
    no `/ 2` rule and used to abstract `↑(r ^^^ r') / 2` as an opaque variable. -/
@[bvify]
theorem ofNat_val_div_two (a : Std.U32) :
    BitVec.ofNat 32 ((↑a : Nat) / 2) = a.bv >>> 1 := by
  have hv : a.bv.toNat = (↑a : Nat) := rfl
  have hlt : a.bv.toNat < 2 ^ 32 := a.bv.isLt
  apply BitVec.eq_of_toNat_eq
  rw [BitVec.toNat_ushiftRight, hv, BitVec.toNat_ofNat, Nat.shiftRight_eq_div_pow]
  simp only [pow_one]
  exact Nat.mod_eq_of_lt (by omega)

/-! ### Value lemmas for `left` / `right` / `parent` / the `direct_path` walk
(pure-`Nat` / `u32`-bit facts, no monad). -/

/-- Bit lemma for `right`: same hypothesis, but xor-ing with `3·2^j = 2^(j+1) + 2^j` clears bit `j`
    and SETS bit `j+1` (clear in `v`), so the value rises by `2^j`. -/
theorem right_val_arith (v j : Nat) (hchar : v % 2 ^ (j + 2) = 2 ^ (j + 1) - 1) :
    v ^^^ (3 * 2 ^ j) = 2 ^ (j + 2) * (v / 2 ^ (j + 2)) + (2 ^ (j + 1) + (2 ^ j - 1)) := by
  have hlow : ∀ i, i ≤ j + 1 → v.testBit i = decide (i < j + 1) := by
    intro i hi
    have h1 := Nat.testBit_mod_two_pow v (j + 2) i
    rw [hchar, Nat.testBit_two_pow_sub_one] at h1
    have hi1 : i < j + 2 := by omega
    simp only [hi1, decide_true, Bool.true_and] at h1
    exact h1.symm
  have h3bit : ∀ m, (3 : Nat).testBit m = decide (m < 2) := by
    intro m; rw [show (3 : Nat) = 2 ^ 2 - 1 from by norm_num, Nat.testBit_two_pow_sub_one]
  have hsh : (3 : Nat) * 2 ^ j = 3 <<< j := by rw [Nat.shiftLeft_eq]
  have step : v ^^^ (3 * 2 ^ j)
      = ((v >>> (j + 2)) <<< (j + 2)) ||| (2 ^ (j + 1) ||| (2 ^ j - 1)) := by
    rw [hsh]
    refine Nat.eq_of_testBit_eq fun i => ?_
    simp only [Nat.testBit_lor, Nat.testBit_xor, Nat.testBit_two_pow, Nat.testBit_shiftLeft,
      Nat.testBit_shiftRight, Nat.testBit_two_pow_sub_one, h3bit, ge_iff_le]
    rcases Nat.lt_trichotomy i j with h | h | h
    · rw [hlow i (by omega)]
      simp [h, show i < j + 1 by omega, show ¬ (j ≤ i) by omega, show ¬ (j + 2 ≤ i) by omega,
        show ¬ (j + 1 = i) by omega]
    · subst h
      rw [hlow i (by omega)]
      simp [show i < i + 1 by omega, show ¬ (i + 2 ≤ i) by omega, show ¬ (i + 1 = i) by omega]
    · rcases Nat.lt_trichotomy i (j + 1) with h1 | h1 | h1
      · omega
      · subst h1
        rw [hlow (j + 1) (by omega)]
        simp [show ¬ (j + 2 ≤ j + 1) by omega, show j ≤ j + 1 by omega]
      · simp [hlow, show j + 2 ≤ i by omega, show j ≤ i by omega, show ¬ (i - j < 2) by omega,
          show ¬ (j + 1 = i) by omega, show ¬ (i < j) by omega,
          show j + 2 + (i - (j + 2)) = i by omega]
  have h1 : 1 ≤ (2 : Nat) ^ j := Nat.one_le_two_pow
  have hp1 : (2 : Nat) ^ (j + 1) = 2 * 2 ^ j := by ring
  have hp2 : (2 : Nat) ^ (j + 2) = 4 * 2 ^ j := by ring
  have hb1 : 2 ^ j - 1 < 2 ^ (j + 1) := by omega
  have hb2 : 2 ^ (j + 1) + (2 ^ j - 1) < 2 ^ (j + 2) := by omega
  rw [step, Nat.shiftRight_eq_div_pow, Nat.shiftLeft_eq, mul_comm,
    Nat.two_pow_add_eq_or_of_lt hb2,
    show (2 : Nat) ^ (j + 1) ||| (2 ^ j - 1) = 2 ^ (j + 1) * 1 ||| (2 ^ j - 1) from by
      rw [Nat.mul_one],
    ← Nat.two_pow_add_eq_or_of_lt hb1, Nat.mul_one]

/-- Range half of `right`'s VCs, pure-`Nat`: with `Q` the high part (divisible by `2^(m+2)`), the
    result `Q + (2^(m+1) + (2^m − 1)) = v + 2^m` still fits `MAX_TREE_INDEX = 2^30 − 2`. -/
theorem right_val_le (Q m : Nat) (hdvd : 2 ^ (m + 2) ∣ Q)
    (hx : Q + (2 ^ (m + 1) - 1) ≤ 2 ^ 30 - 3) :
    Q + (2 ^ (m + 1) + (2 ^ m - 1)) ≤ 2 ^ 30 - 2 := by
  have h1 : 1 ≤ (2 : Nat) ^ m := Nat.one_le_two_pow
  have e1 : (2 : Nat) ^ (m + 1) = 2 * 2 ^ m := by ring
  have e2 : (2 : Nat) ^ (m + 2) = 4 * 2 ^ m := by ring
  have hB : (4 : Nat) ≤ 2 ^ 30 := by norm_num
  -- `m = 29` (i.e. `k = 30`) is ruled out by `hx`: it would force `v = 2^30 − 1 > 2^30 − 3`.
  have hm28 : m ≤ 28 := by
    by_contra hc
    have h30 : (2 : Nat) ^ 30 ≤ 2 ^ (m + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    omega
  obtain ⟨q, hq⟩ := hdvd
  have hpow : (2 : Nat) ^ (m + 2) * 2 ^ (28 - m) = 2 ^ 30 := by
    rw [← pow_add]; congr 1; omega
  have hQlt : Q < 2 ^ 30 := by omega
  have hqlt : q < 2 ^ (28 - m) := by
    by_contra hc
    have h := Nat.mul_le_mul_left ((2 : Nat) ^ (m + 2)) (show 2 ^ (28 - m) ≤ q from by omega)
    rw [hpow, ← hq] at h
    omega
  have hQle : Q ≤ 2 ^ 30 - 2 ^ (m + 2) := by
    have h := Nat.mul_le_mul_left ((2 : Nat) ^ (m + 2)) (show q ≤ 2 ^ (28 - m) - 1 from by omega)
    rw [Nat.mul_sub, Nat.mul_one, hpow, ← hq] at h
    omega
  -- `omega` needs an UPPER bound on the `2^m` atom too (`m ≤ 28` alone is invisible to it).
  have hup : (2 : Nat) ^ m ≤ 2 ^ 28 := Nat.pow_le_pow_right (by norm_num) hm28
  have hB28 : (2 : Nat) ^ 28 = 268435456 := by norm_num
  have hB30 : (2 : Nat) ^ 30 = 1073741824 := by norm_num
  omega

/-- `right_val_arith` in the shape `right`'s VCs present it, delivering
    both facts they need: the result exceeds the tree index, and it stays `≤ 2^30 − 2`. -/
theorem right_bits (v r1 : U32) (k j : Usize)
    (hk30 : (↑k : Nat) ≤ 30) (hkpos : 1 ≤ (↑k : Nat))
    (hchar : (↑v : Nat) % 2 ^ ((↑k : Nat) + 1) = 2 ^ (↑k : Nat) - 1)
    (hj : (↑j : Nat) = (↑k : Nat) - (↑(1#usize) : Nat))
    (hr1 : (↑r1 : Nat) = (↑(3#u32) : Nat) <<< (↑j : Nat) % UScalar.size UScalarTy.U32)
    (hx : (↑v : Nat) ≤ 2 ^ 30 - 3) :
    (↑v : Nat) < (↑(v ^^^ r1) : Nat) ∧ (↑(v ^^^ r1) : Nat) ≤ 2 ^ 30 - 2 := by
  have e1 : (↑(1#usize) : Nat) = 1 := by simp
  have e3 : (↑(3#u32) : Nat) = 3 := by simp
  rw [e1] at hj
  obtain ⟨m, hm⟩ : ∃ m, (↑k : Nat) = m + 1 := ⟨(↑k : Nat) - 1, by omega⟩
  have hjm : (↑j : Nat) = m := by omega
  have hm29 : m ≤ 29 := by omega
  have hchar' : (↑v : Nat) % 2 ^ (m + 2) = 2 ^ (m + 1) - 1 := by
    rw [show m + 2 = (↑k : Nat) + 1 from by omega, show m + 1 = (↑k : Nat) from by omega]
    exact hchar
  have hsh3 : (3 : Nat) <<< m % Aeneas.Std.U32.size = 3 * 2 ^ m := by
    rw [Nat.shiftLeft_eq]
    apply Nat.mod_eq_of_lt
    have h1 : (2 : Nat) ^ m ≤ 2 ^ 29 := Nat.pow_le_pow_right (by norm_num) hm29
    have h2 : (3 : Nat) * 2 ^ 29 < Aeneas.Std.U32.size := by scalar_tac
    omega
  have hval : (↑(v ^^^ r1) : Nat)
      = 2 ^ (m + 2) * ((↑v : Nat) / 2 ^ (m + 2)) + (2 ^ (m + 1) + (2 ^ m - 1)) := by
    rw [UScalar.val_xor, hr1, e3, UScalar.size_UScalarTyU32, hjm, hsh3]
    exact right_val_arith _ m hchar'
  have hdm := Nat.div_add_mod (↑v : Nat) (2 ^ (m + 2))
  rw [hchar'] at hdm
  obtain ⟨Q, hQ⟩ : ∃ Q, 2 ^ (m + 2) * ((↑v : Nat) / 2 ^ (m + 2)) = Q := ⟨_, rfl⟩
  rw [hQ] at hval hdm
  have hle := right_val_le Q m ⟨_, hQ.symm⟩ (by omega)
  have h1 : 1 ≤ (2 : Nat) ^ m := Nat.one_le_two_pow
  have h2 : (2 : Nat) ^ (m + 1) = 2 * 2 ^ m := by ring
  omega

/-- `parent_val_u32` in the shape `parent`'s VCs present it: the extracted code binds each
    shift/mask to its own `r`-variable, so the value equation is re-assembled from those. -/
theorem parent_bits_val
    (v r1 r2 rr : U32) (k k1 : Usize)
    (hk30 : (↑k : Nat) ≤ 30)
    (hchar : (↑v : Nat) % 2 ^ ((↑k : Nat) + 1) = 2 ^ (↑k : Nat) - 1)
    (hk1 : (↑k1 : Nat) = (↑k : Nat) + (↑(1#usize) : Nat))
    (hr2 : (↑r2 : Nat) = (↑v : Nat) >>> (↑k1 : Nat))
    (hr1 : (↑r1 : Nat) = (↑(1#u32) : Nat) <<< (↑k : Nat) % UScalar.size UScalarTy.U32)
    (hrr : (↑rr : Nat)
      = (↑(r2 &&& 1#u32) : Nat) <<< (↑k1 : Nat) % UScalar.size UScalarTy.U32) :
    (↑((v ||| r1) ^^^ rr) : Nat)
      = 2 ^ ((↑k : Nat) + 2) * ((↑v : Nat) / 2 ^ ((↑k : Nat) + 2))
        + (2 ^ ((↑k : Nat) + 1) - 1) := by
  have h1 : (↑(1#u32) : Nat) = 1 := by simp
  have h1' : (↑(1#usize) : Nat) = 1 := by simp
  rw [UScalar.val_xor, UScalar.val_or, hr1, hrr, UScalar.val_and, hr2, hk1, h1, h1',
    UScalar.size_UScalarTyU32]
  exact parent_val_u32 v _ hk30 hchar

/-- Positivity corollary of `parent_bits_val`, shaped for `parent`'s VC blocks: one `have` +
    `scalar_tac` replaces the per-block preamble. -/
theorem parent_bits_pos
    (v r1 r2 rr : U32) (k k1 : Usize)
    (hk30 : (↑k : Nat) ≤ 30)
    (hchar : (↑v : Nat) % 2 ^ ((↑k : Nat) + 1) = 2 ^ (↑k : Nat) - 1)
    (hk1 : (↑k1 : Nat) = (↑k : Nat) + (↑(1#usize) : Nat))
    (hr2 : (↑r2 : Nat) = (↑v : Nat) >>> (↑k1 : Nat))
    (hr1 : (↑r1 : Nat) = (↑(1#u32) : Nat) <<< (↑k : Nat) % UScalar.size UScalarTy.U32)
    (hrr : (↑rr : Nat)
      = (↑(r2 &&& 1#u32) : Nat) <<< (↑k1 : Nat) % UScalar.size UScalarTy.U32) :
    2 ^ ((↑k : Nat) + 1) - 1 ≤ (↑((v ||| r1) ^^^ rr) : Nat)
      ∧ 0 < (↑((v ||| r1) ^^^ rr) : Nat) := by
  have hval := parent_bits_val v r1 r2 rr k k1 hk30 hchar hk1 hr2 hr1 hrr
  have hge : 2 ^ ((↑k : Nat) + 1) - 1 ≤ (↑((v ||| r1) ^^^ rr) : Nat) := by
    rw [hval]; exact Nat.le_add_left _ _
  have h2 : (2 : Nat) ^ ((↑k : Nat) + 1) = 2 * 2 ^ (↑k : Nat) := by ring
  have h3 : 1 ≤ (2 : Nat) ^ (↑k : Nat) := Nat.one_le_two_pow
  omega

/-- Parity corollary of `parent_bits_val`, shaped for `parent`'s VC blocks: one `have` +
    `scalar_tac` replaces the per-block preamble. -/
theorem parent_bits_odd
    (v r1 r2 rr : U32) (k k1 : Usize)
    (hk30 : (↑k : Nat) ≤ 30)
    (hchar : (↑v : Nat) % 2 ^ ((↑k : Nat) + 1) = 2 ^ (↑k : Nat) - 1)
    (hk1 : (↑k1 : Nat) = (↑k : Nat) + (↑(1#usize) : Nat))
    (hr2 : (↑r2 : Nat) = (↑v : Nat) >>> (↑k1 : Nat))
    (hr1 : (↑r1 : Nat) = (↑(1#u32) : Nat) <<< (↑k : Nat) % UScalar.size UScalarTy.U32)
    (hrr : (↑rr : Nat)
      = (↑(r2 &&& 1#u32) : Nat) <<< (↑k1 : Nat) % UScalar.size UScalarTy.U32) :
    (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by
  have hval := parent_bits_val v r1 r2 rr k k1 hk30 hchar hk1 hr2 hr1 hrr
  have hdvd : 2 ∣ 2 ^ ((↑k : Nat) + 2) * ((↑v : Nat) / 2 ^ ((↑k : Nat) + 2)) :=
    Dvd.dvd.mul_right (dvd_pow_self 2 (by omega)) _
  have h2 : (2 : Nat) ^ ((↑k : Nat) + 1) = 2 * 2 ^ (↑k : Nat) := by ring
  have h3 : 1 ≤ (2 : Nat) ^ (↑k : Nat) := Nat.one_le_two_pow
  omega

/-- A node value below `2^30 − 1` has its parent value below `2^30` (the `MAX_PARENT` bound; the
    strict hypothesis is needed since `V = 2^30 − 1` has `k = 30`). -/
theorem parent_val_lt_two_pow_30 (V k : Nat) (hV : V < 2 ^ 30 - 1)
    (hk : V % 2 ^ (k + 1) = 2 ^ k - 1) :
    2 ^ (k + 2) * (V / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) < 2 ^ 30 := by
  have hle : 2 ^ k - 1 ≤ V := by rw [← hk]; exact Nat.mod_le _ _
  have h1 : 1 ≤ (2 : Nat) ^ k := Nat.one_le_two_pow
  rcases Nat.lt_or_ge k 29 with hlt | hge
  · refine parent_lt 29 k _ hlt ?_
    refine Nat.div_lt_of_lt_mul ?_
    rw [← pow_add, show (k + 2) + (29 - 1 - k) = 30 from by omega]
    omega
  · have hk29 : k = 29 := by
      by_contra hc
      have : (2 : Nat) ^ 30 ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) (by omega)
      omega
    subst hk29
    have hq0 : V / 2 ^ (29 + 2) = 0 := by
      apply Nat.div_eq_of_lt
      have : (2 : Nat) ^ 30 ≤ 2 ^ (29 + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
      omega
    rw [hq0, Nat.mul_zero, Nat.zero_add]
    have he : (2 : Nat) ^ (29 + 1) = 2 ^ 30 := by norm_num
    have h1' : 1 ≤ (2 : Nat) ^ (29 + 1) := Nat.one_le_two_pow
    omega

/-- On-path uniqueness: a value below `2^(L+1)` whose trailing-ones count is exactly `L` *is* the
    root value `2^L − 1`. -/
theorem eq_root_of_tones_eq (v L : Nat) (hv : v < 2 ^ (L + 1)) (ht : tones v = L) :
    v = 2 ^ L - 1 := by
  have hm := tones_mod v
  rw [ht] at hm
  rwa [Nat.mod_eq_of_lt hv] at hm

/-- Below the root there is room left in the measure: an on-path `v` strictly inside the tree
    (`v < 2^(L+1) − 1`) that is not the root value has `tones v < L`. -/
theorem tones_lt_of_ne_root (v L : Nat) (hv : v < 2 ^ (L + 1) - 1)
    (ht : tones v ≤ L) (hne : v ≠ 2 ^ L - 1) : tones v < L := by
  rcases Nat.lt_or_ge (tones v) L with h | h
  · exact h
  · exact absurd (eq_root_of_tones_eq v L (by omega) (by omega)) hne

/-- The parent value of an on-path node stays strictly inside the tree: with `size = 2^(L+1) − 1`,
    `k = tones x < L` and `x < size`, the parent value is `< size` (equality is excluded because
    `2^(L+1) − 1` has `L+1` trailing ones while the parent value has `k+1 ≤ L`). -/
theorem parent_val_lt_size (x L k : Nat) (hL : k < L) (hx : x < 2 ^ (L + 1) - 1) :
    2 ^ (k + 2) * (x / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) < 2 ^ (L + 1) - 1 := by
  have hlt : 2 ^ (k + 2) * (x / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) < 2 ^ (L + 1) := by
    refine parent_lt L k _ hL ?_
    refine Nat.div_lt_of_lt_mul ?_
    rw [← pow_add, show (k + 2) + (L - 1 - k) = L + 1 from by omega]
    omega
  have htp : tones (2 ^ (k + 2) * (x / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1)) = k + 1 :=
    tones_parent _ _
  by_contra hc
  have heq : 2 ^ (k + 2) * (x / 2 ^ (k + 2)) + (2 ^ (k + 1) - 1) = 2 ^ (L + 1) - 1 := by omega
  rw [heq, tones_pow_sub_one] at htp
  omega

/-- `level`'s postcondition `v % 2^(k+1) = 2^k − 1` forces `k = 0` on an *even* `v`: for `k ≥ 1`
    the right-hand side is odd while the left-hand side inherits `v`'s parity. -/
theorem level_res_eq_zero {v k : Nat} (hv : v % 2 = 0)
    (hmod : v % 2 ^ (k + 1) = 2 ^ k - 1) : k = 0 := by
  by_contra hk
  have h2dvd : (2 : Nat) ∣ 2 ^ (k + 1) := dvd_pow_self 2 (by omega)
  have hk2 : (2 : Nat) ∣ 2 ^ k := dvd_pow_self 2 hk
  have h2le : (2 : Nat) ≤ 2 ^ k := by
    calc (2 : Nat) = 2 ^ 1 := (pow_one 2).symm
      _ ≤ 2 ^ k := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hmm : v % 2 ^ (k + 1) % 2 = v % 2 := Nat.mod_mod_of_dvd v h2dvd
  rw [hmod, hv] at hmm
  omega

/-! ### The all-ones mask characterization

`TreeSize::valid`'s third conjunct is extracted as the *fixpoint* equation
`s = 2^(log₂ s + 1) − 1`, self-referential in `s` and a `scalar_tac` divergence trigger (reproducer:
`Openmls/Issues/ScalarTacNatLogLoop.lean`).  The two lemmas below convert it to the non-looping mask
test `s &&& (s+1) = 0`; direction B yields a *fresh* existential `∃ k, s = 2^(k+1) − 1`, so no
self-reference reaches `scalar_tac` (with `log2_two_pow_sub_one` the fixpoint is recoverable). -/

/-- Direction A: an all-ones value has no bit in common with its successor. -/
theorem and_succ_eq_zero_of_all_ones (k : Nat) :
    (2 ^ (k + 1) - 1) &&& (2 ^ (k + 1) - 1 + 1) = 0 := by
  have h1 : (1 : Nat) ≤ 2 ^ (k + 1) := Nat.one_le_two_pow
  rw [show 2 ^ (k + 1) - 1 + 1 = 2 ^ (k + 1) from by omega]
  refine Nat.eq_of_testBit_eq fun j => ?_
  simp only [Nat.testBit_and, Nat.testBit_two_pow_sub_one, Nat.testBit_two_pow,
    Nat.zero_testBit, Bool.and_eq_false_iff, decide_eq_false_iff_not]
  by_cases hj : j < k + 1
  · right; omega
  · left; omega

/-- Direction B: `s &&& (s+1) = 0` with `s ≥ 1` forces `s` to be all-ones of some width `k+1`.
    The existential witness is a fresh variable, which is what makes this form safe to feed to
    `scalar_tac` (unlike the fixpoint equation `s = 2^(log₂ s + 1) − 1`). -/
theorem all_ones_of_and_succ_eq_zero (s : Nat) (h1 : 1 ≤ s) (h : s &&& (s + 1) = 0) :
    ∃ k, s = 2 ^ (k + 1) - 1 := by
  set m := tones s with hm
  have hmod : s % 2 ^ (m + 1) = 2 ^ m - 1 := tones_mod s
  have hspec : s.testBit m = false := Nat.find_spec (tones_ex s)
  have hpow : (1 : Nat) ≤ 2 ^ m := Nat.one_le_two_pow
  have hpow' : (2 : Nat) ^ m < 2 ^ (m + 1) := by
    have : (2 : Nat) ^ (m + 1) = 2 * 2 ^ m := by rw [pow_succ]; ring
    omega
  -- `s = 2^(m+1)·q + (2^m − 1)`, hence `s + 1 = 2^(m+1)·q + 2^m`, and both shift to `q`.
  have hdm := Nat.div_add_mod s (2 ^ (m + 1))
  have hq : (s + 1) / 2 ^ (m + 1) = s / 2 ^ (m + 1) := by
    have hsplit : s + 1 = 2 ^ (m + 1) * (s / 2 ^ (m + 1)) + 2 ^ m := by omega
    rw [hsplit, Nat.mul_add_div (by positivity), Nat.div_eq_of_lt hpow', Nat.add_zero]
  -- every bit at or above `m` is clear
  have hhigh : ∀ j, m ≤ j → s.testBit j = false := by
    intro j hj
    rcases Nat.eq_or_lt_of_le hj with rfl | hlt
    · exact hspec
    · have hkey : s.testBit j = (s + 1).testBit j := by
        have e1 : s.testBit ((m + 1) + (j - (m + 1))) = (s >>> (m + 1)).testBit (j - (m + 1)) :=
          (Nat.testBit_shiftRight _).symm
        have e2 : (s + 1).testBit ((m + 1) + (j - (m + 1)))
            = ((s + 1) >>> (m + 1)).testBit (j - (m + 1)) := (Nat.testBit_shiftRight _).symm
        rw [show (m + 1) + (j - (m + 1)) = j from by omega] at e1 e2
        rw [e1, e2, Nat.shiftRight_eq_div_pow, Nat.shiftRight_eq_div_pow, hq]
      have hz : (s &&& (s + 1)).testBit j = false := by rw [h]; simp
      rw [Nat.testBit_and, ← hkey, Bool.and_self] at hz
      exact hz
  have hself : s = 2 ^ m - 1 := by
    rw [← hmod]
    refine (Nat.eq_of_testBit_eq fun j => ?_).symm
    rw [Nat.testBit_mod_two_pow]
    by_cases hj : j < m + 1
    · simp [hj]
    · rw [hhigh j (by omega)]; simp [hj]
  refine ⟨m - 1, ?_⟩
  have hm1 : 1 ≤ m := by
    by_contra hc
    have hm0 : m = 0 := by omega
    rw [hm0, pow_zero] at hself
    omega
  rw [hself, show m - 1 + 1 = m from by omega]

/-- The equivalence used to restate `TreeSize::valid`: under `s ≥ 1`, the extracted fixpoint
    equation and the mask test agree. -/
theorem all_ones_iff_and_succ_eq_zero (s : Nat) (h1 : 1 ≤ s) :
    (s = 2 ^ (Nat.log 2 s + 1) - 1) ↔ s &&& (s + 1) = 0 := by
  refine ⟨fun hfix => ?_, fun hmask => ?_⟩
  · rw [hfix]; exact and_succ_eq_zero_of_all_ones _
  · obtain ⟨k, hk⟩ := all_ones_of_and_succ_eq_zero s h1 hmask
    rw [hk, log2_two_pow_sub_one]

/-- Packages the consumer-side destructuring of the registered mask spec: from the three conjuncts
    of `TreeSize::valid`'s bit form, one `obtain` yields the fresh width `L` together with every
    derived fact the `TreeSize` obligations need (log₂ bridge, `L ≤ 29`, the two power bounds, the
    `pow_succ` doubling, and the shift residue) — replacing the per-site preamble. -/
theorem valid_mask_destruct (s : Nat)
    (h : 1 ≤ s ∧ s ≤ 2 ^ 30 - 1 ∧ s &&& (s + 1) = 0) :
    ∃ L, s = 2 ^ (L + 1) - 1 ∧ Nat.log 2 s = L ∧ L ≤ 29
      ∧ 1 ≤ 2 ^ L ∧ 2 ^ L ≤ 2 ^ 29 ∧ 2 ^ (L + 1) = 2 * 2 ^ L
      ∧ 1 <<< L % Aeneas.Std.U32.size = 2 ^ L := by
  obtain ⟨h1, h2, hmask⟩ := h
  obtain ⟨L, hL⟩ := all_ones_of_and_succ_eq_zero _ (by omega) hmask
  have hlog : Nat.log 2 s = L := by rw [hL]; exact log2_two_pow_sub_one L
  have hL29 : L ≤ 29 := by
    by_contra hc
    have : (2 : Nat) ^ 31 ≤ 2 ^ (L + 1) := Nat.pow_le_pow_right (by omega) (by omega)
    omega
  have hp1 : (1 : Nat) ≤ 2 ^ L := Nat.one_le_two_pow
  have hp29 : (2 : Nat) ^ L ≤ 2 ^ 29 := Nat.pow_le_pow_right (by omega) hL29
  have hpow : (2 : Nat) ^ (L + 1) = 2 * 2 ^ L := by rw [pow_succ]; ring
  have hsh : 1 <<< L % Aeneas.Std.U32.size = 2 ^ L := one_shiftLeft_mod_eq L (by omega)
  exact ⟨L, hL, hlog, hL29, hp1, hp29, hpow, hsh⟩

end openmls
