-- [openmls]: generic, function-agnostic proof infrastructure (concern A).
-- Foundation imported by every other proof module: the measure-decreasing loop driver and its
-- triple helpers, the `Vec` length helper `vecLen`, and the `attribute [spec] uncurry` that lets
-- `mvcgen` step Aeneas tuple-destructuring binds. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/- Lets `mvcgen` step Aeneas tuple-destructuring do-binds (`let (a,b) ← e` desugars to
   `e >>= uncurry (fun a b => …)`). Registered here so it is in scope for every importing module
   before any `Vec`/iterator-heavy `mvcgen`. -/
attribute [spec] uncurry

/-- Length of a `CoreModels` `Vec` (its underlying `Seq`/slice length, as a `Nat`).
    `alloc.vec.Vec T` is reducibly `Seq T = Slice T`, so `v` is itself the slice. -/
def vecLen {T : Type} (v : alloc.vec.Vec T) : Nat := Aeneas.Std.Slice.length v

/-! ### Generic measure-decreasing loop spec (PostCond-flavoured body obligation)

   `Aeneas.Std.loop.spec_decr_nat`'s body obligation is a raw `WP.spec … (fun r => …)`
   predicate, which `mvcgen`/`mspec` will not step through. This variant phrases the body
   obligation as a `⦃ ⇓ r => match … ⌜…⌝ ⦄` Triple, so the body can be discharged with
   `mvcgen`. Adapted from `libcrux-iot` `sha3` `Foundation/I32LoopSpec.lean`
   (`loop_range_spec_i32`). -/
section loop_measure_helpers

abbrev ResultPS := Std.Do.PostShape.except Error (Std.Do.PostShape.except PUnit Std.Do.PostShape.pure)

theorem triple_noThrow_elim {α : Type} {x : Result α} {Q : α → Std.Do.Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ Std.Do.PostCond.noThrow Q ⦄) {v : α} (hv : x = ok v) :
    (Q v).down := by
  subst hv; simpa [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply] using h

theorem triple_noThrow_exists_ok {α : Type} {x : Result α}
    {Q : α → Std.Do.Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ Std.Do.PostCond.noThrow Q ⦄) : ∃ v, x = ok v := by
  match x, h with
  | .ok v, _ => exact ⟨v, rfl⟩
  | .fail _, h => exact absurd h (by simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply])
  | .div, h => exact absurd h (by simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply])

theorem triple_of_ok {α : Type} {x : Result α} {v : α} {P : α → Prop}
    (hx : x = ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply, hp]

/-- Panic-freedom + functional spec for a `loop` driven by a strictly-decreasing `Nat`
    measure, with a `mvcgen`-steppable body obligation. -/
theorem loop_spec_measure {α β : Type} (body : α → Result (ControlFlow α β))
    (measure : α → Nat) (inv : α → Prop) (post : β → Prop) (x0 : α)
    (h_init : inv x0)
    (h_step : ∀ a, inv a →
      ⦃ ⌜ True ⌝ ⦄
      body a
      ⦃ ⇓ r => match r with
        | .cont a' => ⌜ inv a' ∧ measure a' < measure a ⌝
        | .done y => ⌜ post y ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ Aeneas.Std.loop body x0 ⦃ ⇓ r => ⌜ post r ⌝ ⦄ := by
  suffices gen : ∀ (n : Nat) (a : α), measure a = n → inv a →
      ⦃ ⌜ True ⌝ ⦄ Aeneas.Std.loop body a ⦃ ⇓ r => ⌜ post r ⌝ ⦄ by
    exact gen _ x0 rfl h_init
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro a hn hinv
    have hs := h_step a hinv
    obtain ⟨r, hbody⟩ := triple_noThrow_exists_ok hs
    have hpost := triple_noThrow_elim hs hbody
    rw [Aeneas.Std.loop.eq_def, hbody]
    match r with
    | .done y =>
      simp at hpost; exact triple_of_ok rfl hpost
    | .cont a' =>
      simp only at hpost
      obtain ⟨hinv', hlt⟩ := hpost
      subst hn
      exact ih (measure a') hlt a' rfl hinv'

end loop_measure_helpers

/-- `vecLen v` is the length of `v`'s underlying list. -/
theorem vecLen_eq_length {T : Type} (v : alloc.vec.Vec T) : vecLen v = v.1.length := rfl

/-! ### `scalar_tac`-free escape hatch for `Nat.log`-poisoned contexts

   `scalar_tac`'s preprocessing loops on `TreeSize.valid`-shaped hypotheses (they carry
   `Nat.log`/`2 ^ (…) - 1` terms), so goals living in such a context must be closed by `omega`
   on plain `Nat`s instead. These two `rfl`s let `simp only` rewrite a machine-word `<` into
   the `Nat` `<` that `omega` understands, without invoking `scalar_tac` at all. -/

theorem u32_lt_nat (u v : Std.U32) : (u < v) = ((↑u : Nat) < ↑v) := rfl

theorem usize_lt_nat (u v : Std.Usize) : (u < v) = ((↑u : Nat) < ↑v) := rfl

end openmls
