-- [openmls]: PROVED `@[spec]` contracts for standard-library `core`/`alloc` operations.
-- These fill in specs that the extraction did not provide, but — unlike the contracts in
-- `AdmittedCoreSpecs.lean` — they are *discharged here* (no `sorry`), so they are NOT part of the
-- trusted audit surface. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-- `Vec::len` returns the vec's length. -/
@[spec]
theorem vec_len_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.len v
    ⦃ ⇓ n => ⌜ (↑n : Nat) = vecLen v ⌝ ⦄ := by
  unfold alloc.vec.Vec.len vecLen CoreModels.rust_primitives.sequence.seq_len
  mvcgen

/-- `Vec::new` returns an empty vec. -/
@[spec]
theorem vec_new_spec (T : Type) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.new T
    ⦃ ⇓ v => ⌜ vecLen v = 0 ∧ v.1.val = [] ⌝ ⦄ := by
  unfold alloc.vec.Vec.new alloc.vec.VecTGlobal.new vecLen
  mvcgen

/-- `Vec::with_capacity` returns an empty vec. -/
@[spec]
theorem vec_with_capacity_spec (T : Type) (c : Std.Usize) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.with_capacity T c
    ⦃ ⇓ v => ⌜ vecLen v = 0 ⌝ ⦄ := by
  unfold alloc.vec.Vec.with_capacity alloc.vec.VecTGlobal.with_capacity
    alloc.vec.VecTGlobal.new vecLen
  mvcgen

/-- `u32::is_multiple_of` returns exactly the divisibility test `x % y == 0`.
    Total (the `FunsExternal` model is a pure `ok`), so this is proved, not admitted. -/
@[spec]
theorem is_multiple_of_spec (x y : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    core.num.U32.is_multiple_of x y
    ⦃ ⇓ b => ⌜ b = (x.val % y.val = 0) ⌝ ⦄ := by
  unfold core.num.U32.is_multiple_of
  mvcgen
  grind

/-- `u32::leading_zeros` returns the number of leading zero bits: `32` for `0`,
    else `31 - ⌊log₂ x⌋`. Total (the `CoreModels` model is a pure `ok`), so proved here. -/
@[spec]
theorem leading_zeros_spec (x : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    core.num.U32.leading_zeros x
    ⦃ ⇓ r => ⌜ (↑r : Nat) = if x.val = 0 then 32 else 31 - Nat.log 2 x.val ⌝ ⦄ := by
  unfold CoreModels.core.num.U32.leading_zeros
    CoreModels.rust_primitives.arithmetic.leading_zeros_u32
  mvcgen
  unfold Aeneas.Std.core.num.U32.leading_zeros Aeneas.Std.BitVec.leadingZeros
  simp only [Aeneas.Std.UScalar.val]
  have hbv : (x.bv = 0) ↔ (x.bv.toNat = 0) := by
    rw [BitVec.toNat_eq]; rfl
  rcases eq_or_ne x.bv.toNat 0 with h | h
  · rw [if_pos (hbv.mpr h), if_pos h]
    show (BitVec.ofNat 32 32).toNat = 32
    rw [BitVec.toNat_ofNat]
  · rw [if_neg (fun hc => h (hbv.mp hc)), if_neg h]
    show (BitVec.ofNat 32 (32 - Nat.log 2 x.bv.toNat - 1)).toNat = 31 - Nat.log 2 x.bv.toNat
    rw [BitVec.toNat_ofNat]
    omega


end openmls
